### ISSUE TITLE
Pull ScrollToTop into a React hook

### ISSUE THREAD

**Issue by vanshkumar** [SatcherInstitute/health-equity-tracker#1009]
See todo: https://github.com/SatcherInstitute/health-equity-tracker/blob/39990ecc38d09e2c1aebddcb54f14cf3cfc87fb5/frontend/src/App.tsx#L123

Description from Aaron:

Minor code health thing. ScrollToTop should be a hook, not a component (just good React practice to use hooks for things that don't actually display any UI). The link is to a github issue where you can't use location from the root component which is why this is a component, not a hook. Might be able to make it a hook but you'd have to deal with that edge case

**Comment by benhammondmusic** [comment]
Closing this, not sure if it applies since the scroll to top is part of the UI. Plus the edge case seems annoying to deal with. Finally, we may want to consider removing the scroll t top feature anyways; it's overkill for the shorter pages we have
