### ISSUE TITLE
broken layout in whatishealthequity page

### ISSUE THREAD

**Issue by clhenrick** [SatcherInstitute/health-equity-tracker#1014]
When I clicked on the FAQ accordion "what is health equity?" a layout shift occurred and resulted in a broken layout. This happened while viewing the site on a large desktop screen > 2000px width on the latest version of Firefox.

<img width="2998" alt="Screen Shot 2021-07-08 at 2 06 21 PM" src="https://user-images.githubusercontent.com/161748/124991039-fe380d80-dff5-11eb-9a38-10b06c230f5a.png">

**Comment by joshzarrabi** [comment]
Hi @clhenrick 

Thank you so much for pointing this out, and super sorry for taking so long to get back to you! 

We were able to reproduce this issue and will get to work on fixing it !
