### ISSUE TITLE
Add recommended citation

### ISSUE THREAD

**Issue by jgonzalezmsm** [SatcherInstitute/health-equity-tracker#1015]
add somewhere on site. current favorite is under" methodology". Would like to mock up multiple options and scope out effort/work for each one.

“Recommended Citation for the Health Equity Tracker:
Health Equity Tracker. (2021). Satcher Health Leadership Institute. Morehouse School of Medicine. https://healthequitytracker.org/.”

**Comment by benhammondmusic** [comment]
Methodology page would be good. Would "terms of use" also make sense? Is it required that people cite the tracker if they use charts, wording, etc? If so it should be mentioned there for sure. 

One option to consider is to list the actual Citation guide in one single location, and add small unobtrusive links to that single "source of truth" anywhere else that might be helpful. For instance, there could be an FAQ "how do I cite the tracker" and the answer could be "view out our suggested citation [preferred citations]()" which links over.
