### ISSUE TITLE
BQ Schema Structure Design

### ISSUE THREAD

**Issue by slagathorr** [SatcherInstitute/health-equity-tracker#103]
Design a dataset schema that's standardized for the final environment.

**Comment by slagathorr** [comment]
Some environments to keep in mind:

- Dataset for sources where schemas have a detected diff #102 which will (likely) be in a separate project from the data one, possibly the infra project.
- Dataset which has DB views that the export process will pull from.
- Dataset for "cleaned" raw data.
- Dataset for pre-approved manual uploads (also likely in the infra project, not data).

**Comment by slagathorr** [comment]
@ldbnr4 going to start ironing this out, one of the things that we need to do is pick a column for the update date for each row, and apply that across all tables. My suggestion would be a `last_update_ts` and have that as the TIMESTAMP datatype and have that in the UTC timezome. Wanted to pick something now because I'm working on other metadata things that require it, so want to make sure we set it so there's no variance. Thoughts? Yes/No?

**Comment by ldbnr4** [comment]
Do we need to apply this to every row? I would imagine `last_update_ts` will have the same value for every row right?

**Comment by slagathorr** [comment]
Yeah, just adding that column to all tables. Shouldn't add much more data. We can't guarantee that every row is going to be the same because of the possibility of late arriving changes. Even for things that change once every year or two, it'll still be helpful to have just so you can get the latest "batch" easily.

**Comment by ldbnr4** [comment]
As discussed offline, sgtm!

**Comment by slagathorr** [comment]
So it's documented, for that particular field we will be standardizing to having `ingest_ts` across tables with the `TIMESTAMP` data type set to UTC.
