### ISSUE TITLE
Use of "cases per 100k" can be confusing

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1080]
Particularly in variables where users are used to seeing TOTAL reported cases, seeing a CASES/100K can be confusing and easily misinterpreted as the total case count.

Options to clarify include:
- using percentages (instead or in addition to); problematic with very small numbers (e.g. "0.0005%")
- adding the unit (/100k) to every number on bar chart; adds visual noise
- tooltips, etc; not useable on mobile and not immediately visible

**Comment by jgonzalezmsm** [comment]
I think the favorite is adding per 100k in line in each chart and removing it from the x axis. want to mock that up and see if it's too busy?

We could also add a disclaimer/info bubble above the chart explaining why we use per 100k as a metric

**Comment by benhammondmusic** [comment]
@jgonzalezmsm sounds good

**Comment by benhammondmusic** [comment]
mockup with units attached to each bar.... adds visual noise. also hard (impossible?) to style the unit "per 100k"  differently than the number itself
![per 100k label bar chart](https://user-images.githubusercontent.com/41567007/130113581-eeac734f-3f4e-4a36-a159-0aceb12c81d1.png)

**Comment by jgonzalezmsm** [comment]
I think we should scrap this idea. It looks messy and I'm not sure what problem we're solving by adding it on each row.

What do you think about a hover text/definition rather than a disclaimer box? Early on in dev we had certain words stylized differently. If you click on it we can put in a tool tip with a short explanation of per 100k. It could work for mobile too if we treat it as a tap, rather than hover.

For this case, we could make "Cases per 100k" in the title underlined with blue dotted lines, or similar. The user can then click and we populate a tooltip. We could use that design/approach for any terms we'd like to define? and possibly link to the resource page for a glossary/dictionary in the future?

**Comment by benhammondmusic** [comment]
The problem is a real one: that when a user sees a whole number without any other unit attached, the assumption is that it refers to an actual number of people. I agree this mockup above looks busy/messy, but I'm not sure we should totally discount this issue; maybe just keep thinking on it. For reference, it hasn't just been non-science people who have been tripped up by this metric; members of the team who work in public health have also been momentarily confused.

As an example, we wouldn't want to create a chart that showed percentage values, but display them in whole numbers without the "%" sign; this is the same thing... there just isn't a nice little symbol that means "/100k" the way % means "/100".

Perhaps adding a decimal value would cue the user that it wasn't a real number of actual people and was a rate? 
eg "1003.2" instead of "1003"

Or we switch the specific bar chart to display percentage values rather than /100k. This might make the most sense

**Comment by jgonzalezmsm** [comment]
Can we look into making all figures a percentage and maybe drop per100k completely? What would be the most impacted - assuming small populations? Or perhaps we make % a default and per 100k a toggle?

FYI some deep-dive comments from the Google team on visualization that touches on issues with the per100k: https://docs.google.com/document/d/10NWgOvQo1dZFTB0bseLtHXJjGXCFtmM1md81wI_vGbE/edit#heading=h.2jdf2f1i3vdv

**Comment by benhammondmusic** [comment]
Mockup showing fake decimal data (this number is currently rounded earlier in the pipeline, not at the Vega level, so I just added a random decimal amount to show what it would look like)

![add decimal place for 100k clarity](https://user-images.githubusercontent.com/41567007/130261951-a345d158-e3d4-45a3-ae6c-d6bfaf2527f4.png)

**Comment by benhammondmusic** [comment]
Closing this as there is no obvious, clean solution and the few we have tried don't improve the UX overall. We can revisit this if it is identified as a major issue when we have results from our user testing / interviews.
