### ISSUE TITLE
Update copy to reflect EQUITY not simply COVID

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1091]
Throughout entire site, including:

![home covid focused](https://user-images.githubusercontent.com/41567007/129967851-4ec742a0-f08c-4e42-9bda-ff2a3f288d80.png)
![add more equity vs covid language](https://user-images.githubusercontent.com/41567007/129968012-cb611c11-6d03-40e6-bd9d-f186393c726e.png)

**Comment by jgonzalezmsm** [comment]
Let's talk through this with Ebony and team but thinking it's a good move

**Comment by jgonzalezmsm** [comment]
FYI I emailed Ebony today for guidance
