### ISSUE TITLE
add trend icon

### ISSUE THREAD

**Issue by jgonzalezmsm** [SatcherInstitute/health-equity-tracker#1099]
Feature request - as we update data from our sources, can we look against the current value and note whether the update results in an increase, decrease, or no change? I'm thinking in the tool tip as you hover we can add arrow icons. something like this?

![image](https://user-images.githubusercontent.com/81181322/130243729-8ef41033-8d18-4e6b-ab7a-de9c4c8c452c.png)

**Comment by jgonzalezmsm** [comment]
current tooltip for comparison: 

![image](https://user-images.githubusercontent.com/81181322/130244069-8da88109-80ec-4e33-a136-3921480a76db.png)

**Comment by benhammondmusic** [comment]
Just a super quick mockup to show; with the tool tips you can only send in characters (not images or styling as far as I can tell) so we could use a unicode/emoji up character if we want. We'd have to think thru how to display the time frame as well, last updated might imply the current data, but if we want to show the comparison maybe adding something like (4% increase over 2 weeks) or something like that?
![trend over2weks](https://user-images.githubusercontent.com/41567007/130252714-98ae3ec3-e8e7-42e6-8cc3-657b5870d407.png)

https://user-images.githubusercontent.com/41567007/130252717-044cf0bf-004f-4dee-8b3c-723ebb8d2473.mov

**Comment by joshzarrabi** [comment]
We would need to make clear that the latest data is from two weeks before the update date, and that the change would be from a month to two weeks ago

**Comment by jgonzalezmsm** [comment]
i think it looks great! we do note the 2 week period in the methodology page.

can you link in the tooltip? maybe something like "4% change since last update" and make the "last update" link to https://healthequitytracker.org/datacatalog where we can add that detail?

**Comment by benhammondmusic** [comment]
Implementing a hyperlink within vega tooptip: https://vega.github.io/vega-lite/examples/point_href.html

**Comment by jgonzalezmsm** [comment]
Will work on defining this better - but this may be our best bet to fulfill HRSA grant deliverable. Adding this to our board.

**Comment by jgonzalezmsm** [comment]
This will fulfill HRSA time tracking requirement. JC to start PRD to define/mock up

**Comment by jgonzalezmsm** [comment]
Think about this.... since # is cumulative, may be better to express as % of new cases per geo, not total increase 

new cases per race 
new cases per geo 

can show hot spot or %change by population ; highlight % change by population
think of a better term than hot spot since data is a month old

if we leverage hover tooltip, should present somewhere else as well (mainly for mobile or accessibility concerns)

**Comment by jgonzalezmsm** [comment]
jc to send request for proposal 2n, mopdog
