### ISSUE TITLE
Redesign highest and lowest rates dropdown

### ISSUE THREAD

**Issue by jgonzalezmsm** [SatcherInstitute/health-equity-tracker#1100]
The problem with this list is that it seems to reward regions with bad data quality. We don't provide context as to why the regions listed show the highest or lowest rates. Often, it's due to missing or incomplete data and it can be misinterpreted.

![image](https://user-images.githubusercontent.com/81181322/130245757-6ad21836-5285-40a6-9183-edc1d0b371ee.png)

As an alternative, I'd like to explore changing the bullets to show regions with the largest % change in data. Rather than 5 highest rates, we show 5 largest increase/decrease in rates from the previous update. This makes the list more dynamic - it highlights changes in data. It also solves the problem we mentioned earlier where we aren't ranking regions based on incomplete data - just showing % change which supports our other initiatives with tracking unknown data and highlighting biggest jumps/trends in changes.

**Comment by benhammondmusic** [comment]
I wondered it that was why this list box is basically hidden by default? You have to click to expand, and on mobile you can't even read the full title to know what the box will contain:
![highestlowest hidden mobile](https://user-images.githubusercontent.com/41567007/130261355-8e5de1f8-408a-4c5e-8cee-3e73696e9f02.png)

**Comment by jgonzalezmsm** [comment]
It's collapsed by default because it was decided that this is "extra" or "nice to have" info that can be otherwise gathered from the map above. It was a new design element created specifically to show the ranking but it could be more thoughtfully designed... definitely open to changes.

I didn't realize the description cutoff on mobile. Anything we can do to address?

**Comment by benhammondmusic** [comment]
Sure I'll look into it

**Comment by benhammondmusic** [comment]
i tihnk this might be the best option, just shorten the label down for very small screens. It'll still appear as normal on larger screens

![highestlowest mobile terse title](https://user-images.githubusercontent.com/41567007/130268157-c96fec1d-dde0-4298-a792-5c58b45e5b99.png)

**Comment by benhammondmusic** [comment]
it expands to the full title "see the states/territories with the higest and lowest rates" when you expand the box

**Comment by benhammondmusic** [comment]
Just a little thing, but the label verb should change when it's expanded

![hilo see becomes viewing on expand](https://user-images.githubusercontent.com/41567007/130269169-cbc008dd-6bca-4c75-a36b-1c336515f1e6.gif)

**Comment by benhammondmusic** [comment]
Last two things #1101

**Comment by jgonzalezmsm** [comment]
Yeah I like the idea but i think the compare/small multiple map takes a lot more screen real estate so im curious how it would look as a drop down. we link it out so it can be viewed as a larger window
