### ISSUE TITLE
Add dropdown to NAV showing TAB PAGE options

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1127]
The sub pages contained on the material UI tabs are only loosely related, and as we add more and more content (blog, interactive resource page, etc) we will want the user to be able to easily navigate directly to the page they want.

PROPOSAL: 
- add dropdown hover to the existing nav-bar (for desktop) and dropdown toggle submenu (for mobile sidebar nav)
- allowing clicking the top level menu to proceed as normal (eg WHAT IS HEALTH EQUITY), or direct click on a sub tab (WHAT IS HEALTH EQUITY > FAQ)

**Comment by kccrtv** [comment]
Proposed new structure of navigation:

- Home
- About
  - What is Health Equity?
  - Policy Context
  - About Us
- Explore the Data
  - Methodology
  - Data Catalog
  - Data Downloads
- Media & Updates
  - News
  - Videos
- Call-to-Action (CTA) Button
  - Explore the Data
