### ISSUE TITLE
add SHARE button on each chart/map

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1128]

**Comment by benhammondmusic** [comment]
https://github.com/vega/vega-embed/issues/156

**Comment by benhammondmusic** [comment]
This share button could include screenshot functionality (currently the built in Vega "save as PNG" does not include territories or full title)
This share button could also auto format the chart/map for each particular social media platform and automatically share to the user's page

**Comment by benhammondmusic** [comment]
Possible package? 
https://github.com/vre2h/use-react-screenshot

**Comment by benhammondmusic** [comment]
![share email](https://user-images.githubusercontent.com/41567007/137369304-45dbb9b1-de98-4e1b-a023-401801e183bf.png)
![share dialog w icons](https://user-images.githubusercontent.com/41567007/137369333-fc6b49ce-7be9-464c-ba9a-28ca1aeba986.png)
![share email](https://user-images.githubusercontent.com/41567007/137369335-b1fe3b2e-7484-43b6-b201-183ff543d83b.png)
![share fb](https://user-images.githubusercontent.com/41567007/137369340-a51fde69-60ee-40c7-8bb1-7f5d428b54ac.png)
![share linkedin](https://user-images.githubusercontent.com/41567007/137369341-e18a6db7-48f8-4103-abb1-0428899abdaa.png)
![share twitter](https://user-images.githubusercontent.com/41567007/137369343-cf0da49c-5c7e-4046-8291-019d6d21b866.png)

**Comment by jgonzalezmsm** [comment]
Would like to keep this on our radar - after engineering optimizations

**Comment by benhammondmusic** [comment]
closed in #2151
