### ISSUE TITLE
BUG: All metric not shown for territories

### ISSUE THREAD

**Issue by joshzarrabi** [SatcherInstitute/health-equity-tracker#1155]
Right now, when looking at a territory, the 'ALL' metric on top of the map says "no data available"
<img width="1111" alt="Screen Shot 2021-09-14 at 11 45 50 AM" src="https://user-images.githubusercontent.com/3689026/133290455-64cda494-0736-458c-a6ac-7e0aeb0af3c1.png">

This is wrong though, as we do have an 'ALL' metric shown on the bar graph. 
<img width="1083" alt="Screen Shot 2021-09-14 at 11 47 14 AM" src="https://user-images.githubusercontent.com/3689026/133290621-14d70975-cb2b-494f-bd8c-a96bf8f2f739.png">

This is the case for all territories, we should fix this.

**Comment by benhammondmusic** [comment]
What is the correct fix here; obviously we should not display the filter alert for "all", but should we display the breakdown alert in this box instead, as well as in the table below where it appears already? 

![MISSING BREAKDOWN ALERT](https://user-images.githubusercontent.com/41567007/133476110-3e9c0dfc-6ce9-4d47-b260-c33bdf6e945a.png)

Should we allow for the dropdown group selector to appear at all if there are no breakdowns available?

**Comment by benhammondmusic** [comment]
It looks like this is only happening for COVID cases, deaths and hospitalizations. Looking at the other conditions, the way it's properly handled is the `mapQueryResponse.dataIsMissing()` conditionally renders both the missingdataalert or the dropdownmenu

Perhaps this missingdataalert isn't getting properly set for COVID data
