### ISSUE TITLE
Covid Tracking Project Race Data Ingestion and Standardization

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#116]
This only covers the Covid Tracking Project race data (https://covidtracking.com/race), not their general data

**Comment by jenniebrown** [comment]
This issue is also tracking standardization work for CTP data.

**Comment by jenniebrown** [comment]
Closing this since ingestion/standardization steps are complete. I'll file separate issues for cleanup items.
