### ISSUE TITLE
vax bugs to fix

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1174]
- [x] vaccinated "individuals" reported... vs vaccinated in unknowns map ALERT box (one of these is the KNOWN metric sub object)
- [x] should say "county" (not sure where this was on page)
- [ ] NAN% on table 

<img width="1048" alt="nan" src="https://user-images.githubusercontent.com/41567007/134537771-765590ca-1fec-418f-a445-231615d07bcc.png">

**Comment by joshzarrabi** [comment]
@benhammondmusic the solution for the `NaN%` will depend on what we decide to do about showing or not showing the ACS data, so I think we should leave that for now.
