### ISSUE TITLE
Need to standardize grammar, labels, language style

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1184]
- [ ] replace all straight/dumb quotation marks `""` with fancy/smart quotes `“”` when needed as actual quotations. Terms and categories should be indicated using bold tags
- [ ] use of `HET` vs `Health Equity Tracker`
- [ ] need to define what is in the term itself, vs which is a logical combination multiple defined groups. `&`, `and`, `or`. When to use commas? When to use oxford commas? Josh noted CDC uses `/`
- [ ] -use `people` everywhere instead of `individuals` or `persons`
- [ ] use consistent treatment of `data` (singular = more natural, plural = more scientifically accurate)

![and or ](https://user-images.githubusercontent.com/41567007/135490467-e17814a4-94e7-486a-bc91-4deab63a8703.png)

**Comment by jgonzalezmsm** [comment]
hold on this until larger website redesign and copy updates with Mahia
