### ISSUE TITLE
ContextCard

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1200]
We need a way to provide additional context to both the selected Condition and the selected Geography. Currently the PopulationCard does this for the geography. 

Option 1:
- repurpose the PopulationCard as a single space for all context, including missing data alerts, geographic info like population and SVI, and condition info like definition and health equity relevance

Option 2:
- provide two different cards, expanding PopulationCard into GeoCard and adding a new card which will contain the ConditionCard info like definition, data alerts, etc.

Both should be expandable  (like the PopulationCard) and allow important info to display by default, and further exploration on page for interested users

### Condition:
- condition name
- definition (from bottom of report, but shortened to a single sentence if possible)
- brief explanation of WHY this condition is important to measure from a Health Equity perspective
- potentially causal and correlational data sets that highly related 
- potentially an AHR style callout on insights as to who is most affected by this condition
- potentially any context on how these rates have changed over time, and what works to improve these health outcomes

### Location:
- location name
- location population
- SVI / State Health Ranking
- Potentially heat index / days above X degrees, other climate change related hard data
- Consider REMOVING population charts as they may not be very useful?

**Comment by jgonzalezmsm** [comment]
hold on this until we learn more from legal epi work.
