### ISSUE TITLE
Use more inclusive language for category labels

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1236]
Currently `Some other race` is used per CDC terminology; many find this to be a dismissive term and there is room for improvement. We have received feedback from HETF

Additionally, the term `Other` for Sex seems IMHO even worse. Currently the discussion has revolved around our racial categories but we should strongly consider this label as well. Perhaps using the same approach would work: `An unrepresented sex`

**Comment by benhammondmusic** [comment]
What's the status of this change, adding `unrepresented race` instead of `some other race`

Are we waiting for approval from anyone? 

Meanwhile, here is some code I wrote that we may need if/when this is tackled

```
// export const UNREPRESENTED_RACE_DEF = `A single race not
// tabulated by the CDC, not Hispanic/Latino. The definition of
// "Unrepresented Race" is dependent on what other race
// categories exist in the dataset. Please note: The CDC and
// many other sources use the term "Some other race"; we find
// this term to be non-inclusive have avoided its usage.`;
``

**Comment by jgonzalezmsm** [comment]
will discuss this today.

**Comment by jgonzalezmsm** [comment]
received approval, Josh has this in progress.
