### ISSUE TITLE
Move all pct share calculations to backend

### ISSUE THREAD

**Issue by joshzarrabi** [SatcherInstitute/health-equity-tracker#1275]

**Comment by jgonzalezmsm** [comment]
This is probably going to be open a while, right? The goal is to do this for every variable we have (retroactively). Moving forward, this will be the new best practice; does it add complexity to dev work?

**Comment by joshzarrabi** [comment]
@jgonzalezmsm Yeah hopefully we will get to a place where all of these calculations are on the backend, but for new work it shouldnt add any complexity.

**Comment by benhammondmusic** [comment]
closed in favor of #1474
