### ISSUE TITLE
Update language FAQ Data sources

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1282]
![image](https://user-images.githubusercontent.com/41567007/140377505-d5c28f42-a292-4901-8511-dedea109a31f.png)

@jgonzalezmsm what do you think we should change it to?

`Some sources are updated bi-weekly, while other important data (such as information around social determinants of health) can lag from weeks to years`

**Comment by jgonzalezmsm** [comment]
What you wrote looks fine to me, with one addition:

"Some sources are updated bi-weekly, while other important data (such as information around social determinants of health) can lag from weeks to years. **For specific information on update frequent, please visit our Downloads & Methodology page.**"

**Comment by benhammondmusic** [comment]
@jgonzalezmsm  also, should we remove Covid tracking prject from the data sources we use? like, we just link to the data but don't actively use it, correct?

**Comment by benhammondmusic** [comment]
<img width="1344" alt="Screen Shot 2021-11-04 at 1 52 23 PM" src="https://user-images.githubusercontent.com/41567007/140410353-1051ecc5-defe-4eee-b18a-68fd336d3269.png">

**Comment by joshzarrabi** [comment]
We do let people download COVID tracking project data that we have like manipulated to fit with the ACS population numbers we use.

**Comment by joshzarrabi** [comment]
But yeah we don't really use them on the tracker anywhere.

**Comment by jgonzalezmsm** [comment]
I'm okay leaving it but, if we vote to remove it, I would say it's a good fit to move it to the resource page as a historical resource rather than remove it altogether

**Comment by benhammondmusic** [comment]
Cool, ya it's still on the data downloads page and everything; i just removed it from the sentence since it isn't actively used on our tracker.
