### ISSUE TITLE
Suggestion: move bar labels inside bars (when possible)

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1290]
@EbonyRespress suggested a technique of moving the bar labels inside of or overlayed on the largest bars in a visible color and font to help with our issue of wanting more horizontal space to properly show disparities. This should be investigated independently of issues regarding using `k` units / adding explicit `/100k` units to the labels, as horizontal space is at a premium for these charts

**Comment by jgonzalezmsm** [comment]
just noting we received approval to move this to PROD
