### ISSUE TITLE
Update mobile menu home link

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1291]
Seems strange / outdated to call it `Homepage`, we should at least use the word `Home` or better yet match the desktop version and simply link the logo and title "Health Equity Tracker". This reinforces branding and keeps a more consistent UI across devices

![Screen Shot 2021-11-05 at 9 19 13 AM](https://user-images.githubusercontent.com/41567007/140535349-0b514e53-06d3-44c6-9ad2-748636c75e44.png)

**Comment by jgonzalezmsm** [comment]
agree, but low priority. unless you think it's simple/quick
