### ISSUE TITLE
Should we remove "No Data" if there is no grey on the map? 

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1293]
<img width="505" alt="Screen Shot 2021-11-05 at 10 17 34 PM" src="https://user-images.githubusercontent.com/41567007/140597600-7026b687-6bab-403a-8fa1-6178c4d85d49.png">

**Comment by jgonzalezmsm** [comment]
how difficult is this change? i would make it low priority.

**Comment by benhammondmusic** [comment]
closing... seems like not-needed and would clog up the code a bit
