### ISSUE TITLE
Consider building our own backend dashboard for feedback

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1312]
Currently the 3rd party component that collects feedback submits data to a simple backend dashboard that's hosted by the package developer on Heroku. We aren't collecting private info so there aren't serious security implications, but it still would probably be ideal to have our own backend that we could customize and fully control.

MVP: 
- hosted CRUD app with API endpoints that HET and the feedback dashboard could access. Django might be an easy option?
- user authentication to password protect the feedback dashboard

**Comment by jgonzalezmsm** [comment]
If the current solution works and there aren't any maintenance or security concerns then let's roll with this as a ver 1.0 launch. If it gets a ton of usage then we can justify spending time on making our own backend  (i do think its a good idea)

**Comment by benhammondmusic** [comment]
Ya the main concern is if the person who made this open source project isn't maintaining the backend they built it'll just disappear. 

Josh had a good suggestion, we could look into the Google Docs api and just use a sheet file as the "database" that gets updated with new feedback.

**Comment by jgonzalezmsm** [comment]
close this - not enough usage on feedback form; need to reconsider what we need to measure in terms of outreach/feedback/usage
