### ISSUE TITLE
Investigate Google Analytics on UI

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1316]
There are lots of places it would be helpful to understand user behavior that don't always result in a new URL; certain toggle switches, dialogs, upcoming social share functionality, etc. We should outline which user actions we would hope to capture (anonymously) and how to implement those analytics

**Comment by jgonzalezmsm** [comment]
Mahia does have a resource that is very familiar with Google Analytics if we want to bounce questions off of her. Will check with you in the morning so we can draft an email.
