### ISSUE TITLE
Consider generating a table showing data availability

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1320]
on methodology / data showing what is available at each geo level / variable / breakdown

**Comment by benhammondmusic** [comment]
something like this:

<img width="908" alt="Screen Shot 2021-11-19 at 2 24 08 PM" src="https://user-images.githubusercontent.com/41567007/142693499-a05268f7-2757-41df-a450-fb74588c41d6.png">

**Comment by jgonzalezmsm** [comment]
I would work on this as a fun side project :) I think there is a case for it - but if it requires a lot of work I'm not sure when we can justify doing it.

**Comment by benhammondmusic** [comment]
What about pivoted to be from the geo perspective. I can imagine it being very helpful for a casual user to look at their county/state of interest and see a brief description of what variables are available at which demographic breakdowns.

**Comment by jgonzalezmsm** [comment]
close this for now. can maybe leverage #1733 in the future or get design considerations from Ux research project
