### ISSUE TITLE
Consider making "Major Gaps in the Data" shrinkable

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1323]
<img width="1404" alt="Screen Shot 2021-11-19 at 8 15 56 PM" src="https://user-images.githubusercontent.com/41567007/142712818-75ab02bf-d8f6-4e63-b00e-6813bc978bd2.png">
It's a large, attention grabbing box that is very important for users to understand. However, as a user is drilling further and further down into the data, generating multiple reports as they go, it isn't as helpful to continue showing this exact same message, and actually detracts from the tracker as it occupies so much space (pushing potentially related charts further down the page past the "fold")

It would be relatively easy to use either session storage or a cookie to remember when a user has "x'd out" this alert box and let them reclaim that portion of their screen. That way a user is default always shown the message, and a user desiring extra screen space could chose to remove it

**Comment by jgonzalezmsm** [comment]
Curious on other's thoughts on this. I favor keeping it "always on" just because gaps in data is so prevalent.

**Comment by benhammondmusic** [comment]
Group idea: allow user to shrink box down to a single line "major gaps in data"; helps with removing noise while still keeping data issues front and center

**Comment by jgonzalezmsm** [comment]
i think everyone is good for this. add when time allows

final decision: make box collapseable, but the header/tile will remain and cannot be hidden.
