### ISSUE TITLE
Export standardized tables as csv for data downloads

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#133]
This allows serving the original datasets pre-standardization, so users can download from the frontend for reproducibility. We may want to rename the files in a particular way, eg:
covid_tracking_project_standardized
covid_tracking_project_original

**Comment by mayaspivak** [comment]
We decided to provide the standardized version of the data as a csv for download. The exporter needs to be updated to also export as csv for tables with the _std suffix.

**Comment by jenniebrown** [comment]
Duplicate of #137
