### ISSUE TITLE
Need to reorder cards

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1351]
Since we'll be using single column, we need to adjust the card order. Per team meeting, proposed is:

- 100k map
- 100k graph
- unknown map
- disparity graph
- data table

**Comment by jgonzalezmsm** [comment]
do we have an estimate on effort needed to accomplish this?

**Comment by benhammondmusic** [comment]
> do we have an estimate on effort needed to accomplish this?

Should be very easy
