### ISSUE TITLE
Data standardization - standardized FIPS table integration

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#136]
Still an open question whether we want to join this with datasets in the standardization step, since many datasets will need to reference this to add the fips codes anyway, or whether we want to join before export, or whether we just want the frontend to do the display name lookup. Bare minimum is that every dataset has FIPS codes

Also, we should serve the state FIPS and county FIPS files to the frontend as a dataset individually to allow populating frontend UI elements.

**Comment by aaronsn** [comment]
I think @slagathorr had a table like this already set up (geo_ref table in the temporary sandbox), though I think it should be split into one for state FIPS and one for county FIPS for ease of joining. It also needs to be integrated into the pipeline.

**Comment by jenniebrown** [comment]
BigQuery public datasets already publish these tables: bigquery-public-data.census_utility.fips_codes_states and bigquery-public-data.geo_us_boundaries.counties. Would we be comfortable using these tables directly or making copies of them?

**Comment by aaronsn** [comment]
Ooh yeah that seems pretty nice. Counties seem to be under `census_utility.fips_codes_all`. We should probably double-check that it has all of the states/counties/territories

**Comment by vanshkumar** [comment]
Moving to backlog as this doesn't seem critical for launch
