### ISSUE TITLE
Data server should support export as csv or json

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#137]
Frontend requires json for charts and csv for downloads

**Comment by aaronsn** [comment]
@jenniebrown @mayaspivak

**Comment by mayaspivak** [comment]
Are any of the sources ingested as json instead of csv? If so, should we convert to csv for download? Or should the download be in the original format?

**Comment by jenniebrown** [comment]
The census api provides the data in json, I'm not sure about other sources. My instinct would be to provide everything in csv format for download for consistency and because I think that is the most common.

**Comment by mayaspivak** [comment]
Currently the data server assumes all exported files in GCS are newline delimited json and transforms them before serving to the frontend. If a requested file has a .csv suffix, the data should not be transformed. This check needs to be added to the data server code.
