### ISSUE TITLE
On methodology we should outline WHY for each source we are using

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1372]
- [ ] in the methodology stress the reason why we wanted to specifically highlight opioid use as a subset of that data source because of the prevalence of that crisis. Kind of like how we that overarching message regarding racism and its relationship to scarce data, we could include the need to highlight opioid use. 
- [ ] same for all existing conditions

**Comment by jgonzalezmsm** [comment]
Assign to JC - to start next sprint

**Comment by jgonzalezmsm** [comment]
track under #1706
