### ISSUE TITLE
Idea: hover box showing outline of tracker cards and user position on the page

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1383]
We have discussed a feature that has a hover box on the side of the tracker to outline all cards available, and showing the user where they are and what other cards (off screen) are available. This would be the ideal behavioral, and this would track which specific card was "in view" and re-scroll the user to the equivalent scroll position with new tracker position.

**Comment by benhammondmusic** [comment]
I think we could use the MUI `Stepper` for this and stay in line with the MUI components we are already using. Look at the right hand sidebar of this video:


https://user-images.githubusercontent.com/41567007/147702679-5d4b9547-5c54-4bbd-b114-da4c3a6969db.mov

**Comment by benhammondmusic** [comment]
https://css-tricks.com/sticky-table-of-contents-with-scrolling-active-states/

https://css-tricks.com/sticky-smooth-active-nav/

**Comment by jgonzalezmsm** [comment]
#1733
