### ISSUE TITLE
MadLib should smoothly animate between Sticky and Non-sticky size

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1385]
Right now it's a clunky hard switch between the larger height madlib (with carousel controls) and the shorter "sticky" madlib that tracks as you scroll down on desktop. It'd be super nice to have this size transition smoothly rather than an abrupt, discrete change.

https://user-images.githubusercontent.com/41567007/147723769-848334e0-6558-4de9-b962-30cd8f8b72ea.mp4

**Comment by jgonzalezmsm** [comment]
get a size estimate on this and work as time allows. if it's too much effort then i recommend removing from backlog to prioritize later.
