### ISSUE TITLE
Post-launch blog items

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1399]
Helpful things to add/do concerning the blog. Not essential for MVP

- [ ] add styling for blog tables (centered content, alternating background color for rows, padding/margin
- [ ] documentation for developers (structure, GCP info, server info for WP host)
- [ ] add new blog components to storybook once storybook is up to date

**Comment by jgonzalezmsm** [comment]
Recommend hold on this except for the documentation for developers bullet.
