### ISSUE TITLE
Implement AXE linter for CI/CD

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1402]
AXE linter checks code for baseline A11y items. As a VSCODE extension if checks the file you are working on, but it can also be implemented as an automated check via GitHub actions (like how we run eslint). This will help all new frontend code to stay compliant with A11y basics

**Comment by joshzarrabi** [comment]
This is a great idea.

**Comment by benhammondmusic** [comment]
https://github.com/dequelabs/axe-core-npm

**Comment by benhammondmusic** [comment]
The SatcherInstitute github account isn't registered as "personal" so I can't install the automated tool via GitHub. Perhaps it's possible to configure manually.

**Comment by benhammondmusic** [comment]
Maybe this [package](https://www.npmjs.com/package/@axe-core/playwright)
