### ISSUE TITLE
Request: add more COVID by county key phrases

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1428]
- Covid-19 deaths by race at the state and county level
- Covid-19 cases by age at the state and county level
- Covid-19 deaths by age at the state and county level

Ideas for placement: Project Tab, Methodology, Home Page, bottom of Explore Data Page

_Originally posted by @joshzarrabi in https://github.com/SatcherInstitute/health-equity-tracker/issues/1106#issuecomment-1029089297_

**Comment by jgonzalezmsm** [comment]
If this is quick and easy let's add it for SEO. I can go through the pages and offer up where exactly to place the terms. Let's have a quick chat on this
