### ISSUE TITLE
Define the Determinant Categories

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1431]
## To Do

- [ ] Decide which categories should be defined. Note: it will simply display the category name by itself if there is no category definition provided.
- [ ] Finalize category definitions.

Email sent to team:
Good morning! I implemented the code that adds category names and placeholder definitions on both the methodology page and the explore data page (where the definitions are currently populated). The only things missing are the actual definitions. I’ve coded it in a way that the definitions are optional, in case we decide some of the categories don’t require definitions.

• COVID-19
• Chronic Disease
• Social and Political Determinants of Health
• Behavioral Health

1. Which of these categories should we have definitions for?
2. Do these definitions currently exist, and if not who is best suited to create them?

**Comment by jgonzalezmsm** [comment]
Can document work on  #1706
