### ISSUE TITLE
Make a preview mode for new blog posts

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1445]
It might be helpful for blog writing to have a new route like `healthequitytracker.org/previewblog` that displays ONLY posts marked as "preview". This would simplify the production code for the normal blog.

Unfortunately I don't believe we can use the built in wordpress "private" option because it would require user auth; instead we are using a custom boolean value that can be turned on/off in the wordpress dashboard. Any where "preview" is turned on would appear at a netlify deploy route and could be used as a preview of the "real" thing

```
// hide selected posts on production but not dev so authors can use dev for a preview

function hidePostsOnProd(articles: Article[]) {
  // deploy-preview-1444--health-equity-tracker.netlify.app
  // dev.healthequitytracker.org
  // healthequitytracker.org
  if (window.location.hostname === "deploy-preview-1444--health-equity-tracker.netlify.app")
    return (articles = articles.filter(
      (article) => article.acf.hide_on_production !== true
    ));

  return articles;
}
```

**Comment by jgonzalezmsm** [comment]
Recommend hold on this - users are still not trained on current state and due to low frequency of blog posts expected they can just use what is designed for now.

**Comment by jgonzalezmsm** [comment]
let's not spend time on this. Mahia is comfortable posting, reviewing, and making edits as needed.
