### ISSUE TITLE
create code release process for production

### ISSUE THREAD

**Issue by slagathorr** [SatcherInstitute/health-equity-tracker#145]
Followup from standup meeting regarding github code release process for production. Covers documentation for this process.

**Comment by aaronsn** [comment]
Btw, based on prior discussions, when we migrate the frontend to Cloud Run/Terraform, we will want that to have a separate prod release branch from the pipeline

**Comment by vanshkumar** [comment]
Looks like Maya already did the documentation for this here: https://docs.google.com/document/d/11KpnUwdDpsq06rIsBXX0BjyPp7BkvNxgM2TWqC31V3Q/edit

Changing the focus of this bug to improving the prod release process & moving to backlog for now
