### ISSUE TITLE
A11y Doc / Report

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1456]
Reframe as ACCESS issue, which is inclusive of digital A11y for those with disabilities, along with the ability to access the information easily regardless of device size, power, or the speed of the internet connection

- [ ] JC and Ben create write-up and potentially short video / screen shot content of screen reader demonstrating massive gains in A11y.

- [ ] Send to Nelson to update the group he met with last fall

- [ ] Mahia social share.

**Comment by benhammondmusic** [comment]
Link to doc in progress: https://docs.google.com/document/d/1n7V1KstUK1X4K3ObZJgErNDTcjSUiyQYwicpYSnv8iw/edit#

Link to report sent to Nelson in October; should recreate this report with important updates and subsequent check boxes completed: https://docs.google.com/document/d/1H41Ukl2tGpFOAIBYynFq7TLCyMlJeWPIPfpVhXhMLOM/edit#heading=h.338pn3o2wws2

**Comment by jgonzalezmsm** [comment]
I requested access to doc. I would say this is low priority for now - but may be a good update to include in our 1year anniversary project in May. This could be a topic on the pamphlet. Will discuss further.

**Comment by benhammondmusic** [comment]
closing as this is now a report for no-one. we should still highlight the work we do to improve accessibility for data visualizations
