### ISSUE TITLE
Update Vega-embed

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1460]
My A11y updates were merged, so we can update this package. However it's a nested dependency of react-Vega so some additional work needs to be done to force the more recent sub dependency

**Comment by jgonzalezmsm** [comment]
Please define effort and if it's something you can tackle soon let's do it - otherwise put on hold until we sync on roadmap as a team.

**Comment by benhammondmusic** [comment]
Looks like the package we use that uses the one I fixed a level up has already propagated the change. Meaning the a11y improvements are now live for everyone using `react-vega`
