### ISSUE TITLE
Remove estimated_total calculations from BRFSS provider

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1466]
Eventual goal of migrating all calculations to the backend

@benhammondmusic Can we add a todo to delete these

_Originally posted by @joshzarrabi in https://github.com/SatcherInstitute/health-equity-tracker/pull/1437#discussion_r808403108_

**Comment by joshzarrabi** [comment]
Closed in favor of: https://github.com/SatcherInstitute/health-equity-tracker/issues/1476
