### ISSUE TITLE
Covid Tracking Project Aggregation and Export

### ISSUE THREAD

**Issue by jenniebrown** [SatcherInstitute/health-equity-tracker#147]
This is a tracking issue for identifying aggregations and writing aggregation routines for CTP race data.

**Comment by jenniebrown** [comment]
We definitely want to join with FIPS codes. We also (probably) want to join with ACS population data. There are some states and territories which don't report any race data (reports_race or reports_ethnicity == 0). In those cases, we should not compare to population.

The only aggregation we want to do is to the national level, which should be done for both CRDT and population (don't use total US population from ACS, use aggregate from state/territory pops).

**Comment by jenniebrown** [comment]
We will export 4 CRDT tables:

covid_tracking_project_cases_std
covid_tracking_project_deaths_std
covid_tracking_project_hosp_std
covid_tracking_project_tests_std

**Comment by vanshkumar** [comment]
Joining CTP data with ACS is the only thing left here, moving to backlog
