### ISSUE TITLE
Move all state level vaccine calculations to the backend

### ISSUE THREAD

**Issue by joshzarrabi** [SatcherInstitute/health-equity-tracker#1480]
##  Background 

Currently, our state level vaccine processing is a mish mash of complicated code handling a bunch of different cases. The reason for this is because the Kaiser Family Foundation presents the numbers in a bunch of different ways and we have to have cases for each of them. 

The current structure is as follows:

* Get the raw numbers for state total vaccinations from the kff [in python](https://github.com/SatcherInstitute/health-equity-tracker/blob/281052a957b096a26aac28c79766a2be62d0c7dc/python/datasources/kff_vaccination.py#L145-L159)

* Get the percentages of each race of people vaccinated, and the population pct defined by the KFF from the KFF [in python](https://github.com/SatcherInstitute/health-equity-tracker/blob/281052a957b096a26aac28c79766a2be62d0c7dc/python/datasources/kff_vaccination.py#L112-L142)

* Merge the state total population numbers using [big query sql](https://github.com/SatcherInstitute/health-equity-tracker/blob/main/config/data_sources/AGG_kff_vaccination.sql)

* Multiply the `pct_share`, `population_pct_share` and `vaccinated_pct` by the correct constants to get the correct corresponding numbers [on the frontend](https://github.com/SatcherInstitute/health-equity-tracker/blob/main/frontend/src/data/variables/VaccineProvider.ts#L93-L124)

* Calculate the per_100k metric for TOTAL population [on the frontend](https://github.com/SatcherInstitute/health-equity-tracker/blob/281052a957b096a26aac28c79766a2be62d0c7dc/frontend/src/data/variables/VaccineProvider.ts#L140-L147).

## Why is this bad

The frontend code is very complicated and slower than it needs to be. Its weird that our `TOTAL` row in the big query table has a raw count of vaccination while the other races have percentages.

## Proposed Implementation
Every row on the big query table should have the same, correctly filled out columns 

* `vaccinated_pct_share`
* `vaccinated_per_100k`
* `population_pct`
* `acs_vaccine_population_pct`

## End State

- [ ] I can log onto big query and see the above columns filled out in the `kff_vaccination.race_and_ethnicity` table
- [ ] [This code](https://github.com/SatcherInstitute/health-equity-tracker/blob/281052a957b096a26aac28c79766a2be62d0c7dc/frontend/src/data/variables/VaccineProvider.ts#L93-L162) is deleted

**Comment by benhammondmusic** [comment]
@joshzarrabi if we are merging multiple data sources into the backend, we have to signify that somehow on the frontend for our source footers. If this isn't already covered in #283 we should file an issue to handle this citation side of things

**Comment by joshzarrabi** [comment]
@benhammondmusic  Yes, that is a good point something we definitely need to address this. We can easily add it manually right now which is what we have been doing
