### ISSUE TITLE
second card isn't appearing when it should be partially on screen

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1492]
**Describe the bug**
Currently all of the cards other than the 1st (100k map card) are lazy loaded for performance. However, on some views that map isn't available, and the height is much shorter. This isn't accounted for in the 2nd cards offset for lazy loading, making it appear that there aren't any other cards available (until you scroll down and then it appears)

**To Reproduce**
(https://healthequitytracker.org/exploredata?dt1=hospitalizations&mls=1.cardiovascular_diseases-3.06)

**Expected behavior**
offset needs to be smaller or removed for the second card

**Screenshots**
<img width="885" alt="Screen Shot 2022-02-28 at 1 50 09 PM" src="https://user-images.githubusercontent.com/41567007/156056841-753e006d-c956-4f6c-a900-6d3dede806fa.png">

**Comment by joshzarrabi** [comment]
Good catch
