### ISSUE TITLE
Remove unused `Race` Columns

### ISSUE THREAD

**Issue by joshzarrabi** [SatcherInstitute/health-equity-tracker#1496]
## Describe the bug

Currently, with each row for a race demographic, [we send four columns to the user](https://github.com/SatcherInstitute/health-equity-tracker/blob/e31c2329ff95b90a83a26d270753c5f01f286dc2/python/ingestion/standardized_columns.py#L81-L86):

* `race_category_id`
* `race`
* `race_includes_hispanic`
* `race_and_ethnicity`

All of these rows are based off of `race_category_id` and are essentially duplicated information.

We originally built this in anticipation of the CDC splitting race and ethnicity into separate columns, but that doesn't seem to be happening at any point soon (or ever).

The only two rows we actually end up using are

* `race_category_id` as an easy way to compare racial groups
* `race_and_ethnicity` as a text representation of the race we show to the user

The other two columns are never used. 

## Why is this bad

* It adds two extra rows of data we have to send to the user, bloating file size.
* Its annoying to have to ship these pieces of data around, especially because `race_includes_hispanic` is our only boolean so we have to do lots of [special casing for it](https://github.com/SatcherInstitute/health-equity-tracker/blob/e31c2329ff95b90a83a26d270753c5f01f286dc2/python/datasources/cdc_restricted.py#L49-L50)

## Proposed Solution

Let's get rid of the `race` and `race_includes_hispanic` columns.

## Notes

If the cdc does actually end up splitting out race/ethnicity we should reassess, and come up with an actual plan of how we want to show that information to the user.

**Comment by benhammondmusic** [comment]
Should we still remove the extra columns for now, despite knowing the CDC plans to split race/ethnicity?

**Comment by joshzarrabi** [comment]
Closed in favor of #1936
