### ISSUE TITLE
Allow for individual manual uploads

### ISSUE THREAD

**Issue by ldbnr4** [SatcherInstitute/health-equity-tracker#159]
Refactor the ManualUploads class and create new DAGs to allow for single file manual uploads from GCS to BQ.

The DAGs for manual upload will differ from the other typical ingestion DAGs by implementing only one step of the pipeline (gcs to BQ). The pre-existing ManualUploads class can be modified to take a specific GCS file name as an input and write the data to BQ.

**Comment by ldbnr4** [comment]
[DAGs directory](https://github.com/SatcherInstitute/health-equity-tracker/blob/master/airflow/dags) - code location for adding new individual manual upload DAGs for each data source.

[ManualUploads class](https://github.com/SatcherInstitute/health-equity-tracker/blob/master/python/datasources/manual_uploads.py) - current class that uploads all files in the manual uploads GCS bucket.

**Comment by vanshkumar** [comment]
Since we have not prioritized data which requires manual uploads before the April MVP launch (except for CTP metadata, which Jennie already has a DAG for), going to work on the new data sources rather than spending time on this issue
