### ISSUE TITLE
Need County SVI on Population Card and Map Hover Tooltips

### ISSUE THREAD

**Issue by joshzarrabi** [SatcherInstitute/health-equity-tracker#1611]
## Is your feature request related to a problem? Please describe.

The [Social Vulnerability Index](https://www.atsdr.cdc.gov/placeandhealth/svi/index.html) is a ratio generated by the CDC that shows how vulnerable a county is to disasters and disease outbreaks. Closer to 0 means less socially vulnerable and closer to 1 means more socially vulnerable.

This gives the user context on the overall level of environmental and economic suffering in a county when looking at any of our other metrics.

Multiple users have asked us for this and it is something we have been discussing for a while.

## Describe the solution you'd like
When the user looks at the county level data they should be able to see the SVI of the county. 

I believe we should use the `RPL_THEMES` key from the SVI csv.

- [x] The user should be able to see it in the population card. Done in #1630 
- [x] Somewhere on the page the user should be able to see an explanation on what the SVI means. Done in #1630 
- [x] Methodology should be updated with SVI stuff
- [x] Updating `frontend/src/data/config/DatasetMetadata.ts` with the new datasetid so that the Sources footer populates on the PopulationCard whenever SVI is loaded (and eventually on the Map card(s) as well when we pull in the SVI info for the hover box)
- [x] Updating `frontend/src/data/config/MetadataMap.ts` so that the Data source appears and users could download a csv with our data
- [x] Adding SVI to the hover tooltip on STATE level report maps that are displaying COUNTIES
- [x] Linking from the Population card directly to the SVI section of the methodology using HashRouter
- [x] Ensure colors used for SVI are > 4.5 contrast (medium is currently 3.59)

<img width="1101" alt="Screen Shot 2022-07-15 at 4 36 04 PM" src="https://user-images.githubusercontent.com/41567007/179321457-a5675e39-736d-41d5-a264-802b366c1a55.png">
<img width="1352" alt="Screen Shot 2022-07-15 at 4 37 29 PM" src="https://user-images.githubusercontent.com/41567007/179321459-462456b9-82e6-4cd7-95c9-98af992982cb.png">
<img width="777" alt="Screen Shot 2022-07-15 at 4 48 43 PM" src="https://user-images.githubusercontent.com/41567007/179321576-e095160a-a651-4a36-88f7-aadfb5fc7b5c.png">

**Comment by jgonzalezmsm** [comment]
<img width="1179" alt="Screen Shot 2022-06-01 at 12 09 30 PM" src="https://user-images.githubusercontent.com/81181322/171450274-9be3cc9e-9048-409f-8b63-7aac64328cff.png">

something to kick off brainstorming

**Comment by joshzarrabi** [comment]
@jgonzalezmsm Looks great, but I dont think we should say that we have it at the county level. We should just put it on the county level and say what it is.

**Comment by joshzarrabi** [comment]
For sure, I do want to be aware of adding to much extra text to the page. Either way I think this issue should just focus on SVI at the county level. We should think about State Healthcare Rank and state level later.
