### ISSUE TITLE
Request new geographical breakdown

### ISSUE THREAD

**Issue by eriwarr** [SatcherInstitute/health-equity-tracker#1669]
**Is your feature request related to a problem? Please describe.**
This issue is related to PR #1630. Currently, we are using the Age breakdown in order to filter the SVI data. A new breakdown type needs to be created to apply to geographically related data i.e. county-specific data.

**Describe the solution you'd like**

**Describe alternatives you've considered**
The code is currently applying the age breakdown to the data frame in order to get a temporary working solution to bring in the SVI data. This alternative needs to be updated as Age is not a breakdown that applies to SVI data.

**Comment by benhammondmusic** [comment]
This was implemented in #1957; some data on the backend is still only available with breakdown by race, age or sex, but our data for things like SVI is now stored without and demographic column info. On the frontend it can also be loaded in without and demographic breakdown
