### ISSUE TITLE
Time tracking

### ISSUE THREAD

**Issue by joshzarrabi** [SatcherInstitute/health-equity-tracker#1699]
## Background
Many users have asked us about the ability to track health equity topics over time. Some have even gone as far as to describe our current iteration as a "health equity snapshot" as opposed to a health equity tracker. 

Furthermore, we got a grant to implement this and accepted it so we are going to do it. 

## What's Missing / Problems with the current approach
Currently there is no way to track changes in health equity topics over time. Every metric is simply a snapshot of the most recently updated version. 

## Proposed Solution
Work with 2N to design a way to view both the `per100k` and the `pct_share` metrics for each demographic in a specific geography over time, and then do the work to get all the needed old versions of the data on the backend.

We will use our COVID dataset to start off with because it is the most rich dataset, and the simplest to work with as the latest version of the COVID data has all historical data, and we can choose the time frame as we have the data down to the day.

After that we will go through each dataset one by one and pull in old versions of the data. [Here](https://docs.google.com/document/d/1-4-neD0EAmtu0hJ65InB5u0_D9ETi4LYLdJ1m4IbMVs/edit#) we document how much historical data there is for each datasource.

## Screenshots / Mockups
Coming soon

#### Stage 1 

We have working visualizations tracking the `pct_share` `per_100k`, and `unknown_pct` metrics for all COVID geographic and demographic pairs over the length of the pandemic (starting Jan 2020).

#### Stage 2

All datasources are plugged into the new visualizations and users can see them over time. 

## How will this move the needle on health equity?
Specifically how this will help advance health equity, and is possible who the target audience might be (policy influencers, non-technical users, etc)

Users can see the impact that policy has on health equity outcomes.

## Tasks:

- [x] https://github.com/SatcherInstitute/health-equity-tracker/issues/1703
- [x] #1717

**Comment by jgonzalezmsm** [comment]
close this, open new issue for each topic
