### ISSUE TITLE
Add a time dimension for all COVID metrics

### ISSUE THREAD

**Issue by joshzarrabi** [SatcherInstitute/health-equity-tracker#1703]
**Is your feature request related to a problem? Please describe.**

PRD Here: https://docs.google.com/document/d/1WSdPSvww4njifeSR0Y2niZkwZIQ3InTv8wl9aaTGZt8/edit#heading=h.5h2374q35fo4

As described in #1699, we plan to add time based metrics to every health equity metric on the site.

We will do the COVID dataset first because, due to its line item origin, it provides the richest and most customizable data. Furthermore, each line has a specific symptom onset date, and, crucially, the latest version of the data contains *all* of the data. Thus, we can mold the data in any way that we want without having to tackle the complexity of storing multiple versions of the same dataset, which we will need to do to add time to any other dataset. 

We are working with the 2N design agency to design new visualizations for the `per_100k`, `pct_share`, and `unknown_share` metrics that show change over time, and we will adjust the schema based on the outcome of the design.

**Describe the solution you'd like**

So far the currently proposed flow will be to change the outputted data schema so that there is an extra column representing the month in which a covid patient first reported symptoms. 

Currently the data looks like:

| sex | state_fips | covid_cases |
| --- | ---- | --- |
| Male | 06 | 10
| Female | 06 | 5
| Unknown | 06 | 1

But after this I propose it would look like:

| sex | state_fips | covid_cases | time_period |
| --- | ---- | --- | --- |
| Male | 06 | 5 | 2021-02 |
| Female | 06 | 2 | 2021-02 |
| Unknown | 06 | 0 | 2021-02 |
| Male | 06 | 5 | 2021-03 |
| Female | 06 | 3 | 2021-03 |
| Unknown | 06 | 1 | 2021-03 |

--------------------------------------------------

### To transform into a time series dataset

Then, as we need a time series dataset, we need to transform the tables into a time dataset where each demographic category would be a key, with a value that is a list of (timestamp, value) tuples. ~We need to decide if this transformation happens on the backend or with d3 on the frontend.~ 

As we do not have a good way to store time series data in big query (I think its possible but does not match with our current workflow), I think we should try to do the transform on the frontend using d3.

So for example the per_100k series would look something like:

| Asian | Black |
| --- | ---- |
| (2021-02, 10,000), (2021-03, 11,000) | (2021-02, 5,000), (2021-03, 7,000) |

In order to keep the pattern of `(timestamp, value)` consistent for the `pct_share` metric, we have decided to make the value the delta between the pct share and population percentage for each row of data, creating a sort of burden of disease datapoint that can be graphed over time. So, for example, if in `2021-06` Hispanic people had a population percentage of 40%, and covid_cases_share of 60%, their `burden of disease delta` would be `+20`, and if white people made up 50% of the population and 10% of cases their `burden of disease delta` would be `-40`.  We need to make sure users understand what this metric means.

Note: 

* Fixing the null vs zero case will also resolve an issue where the `pct_share` of nulled out deaths and hospitalization states for the `ALL` demographic are showing up as 100% instead of null

TODO:

- [ ] [Fix null vs zero case](https://docs.google.com/document/d/1LtWyd8lxZ4S-Zg3UNqhzniQ8DML_ZYH9tSw-IQ2HJiQ/edit?resourcekey=0-3eq4gC6UBOys9TPofCTEEQ#heading=h.972apg45bz2j)
- [x] Write more tests
- [ ] Write copy describing the graphs for the methodology page
- [ ] Think about what to do about fully unknown outcome rows.

**Comment by benhammondmusic** [comment]
This is awesome  @joshzarrabi   One thought I had, should we encode the time (for variables in general) as a time stamp that would work no matter what the time unit is? In other words; if we had data by day, by month, or by year the time would be captured in a standardized way that wouldn't require weird string manipulation to handle and instead could follow consistent in built time methods

**Comment by joshzarrabi** [comment]
@benhammondmusic I think thats a cool idea and pandas has lots of good time functions. For now I'm just keeping it as a string because the `to_datetime` function on pandas is pretty inefficient and running that on 80 million records was making the script take even longer. I was reading there are some ways we can speed it up though so its definitely something we can look into.

**Comment by benhammondmusic** [comment]
@joshzarrabi also wondering if the column name should be like "incidence_time" or something like that. I think it'll get confusing to use the term "period" when we really want to treat it as a single point in time. The word "period" implies start and end points. 

The other option is we treat ALL our variables as monthly, and the yearly data like AHR we simply encode as January of whatever year the report is released

**Comment by joshzarrabi** [comment]
> @joshzarrabi also wondering if the column name should be like "incidence_time" or something like that. I think it'll get confusing to use the term "period" when we really want to treat it as a single point in time. The word "period" implies start and end points.
> 
> The other option is we treat ALL our variables as monthly, and the yearly data like AHR we simply encode as January of whatever year the report is released

@benhammondmusic Yeah, I think we should change the name. The issue is it is a period, as the cases associated with a month could have happened *any* day of the month.
