### ISSUE TITLE
SVI not showing when other metrics are not available

### ISSUE THREAD

**Issue by eriwarr** [SatcherInstitute/health-equity-tracker#1712]
@eriwarr Noticed something interesting; if the 100K isn't available it doesn't display the SVI. I think that's fine for now, but should we try and make it so it shows the SVI regardless of the presence of the other metric? 

<img width="1398" alt="Screen Shot 2022-07-21 at 3 50 19 PM" src="https://user-images.githubusercontent.com/41567007/180321318-671687a4-11b2-4e6b-ae40-0ba243253d98.png">
<img width="1398" alt="Screen Shot 2022-07-21 at 3 50 22 PM" src="https://user-images.githubusercontent.com/41567007/180321322-8b9c0c4f-1fdd-4ce7-8e70-4cf7fc8a11d4.png">

_Originally posted by @benhammondmusic in https://github.com/SatcherInstitute/health-equity-tracker/issues/1702#issuecomment-1191970648_

**Comment by jgonzalezmsm** [comment]
If we have SVI let's show it. 

treat this as a side-project (work as time allows).

if it's a lot of effort / complex then remove from backlog to prioritize later.
