### ISSUE TITLE
Add Census Race group definitions to methodology page

### ISSUE THREAD

**Issue by joshzarrabi** [SatcherInstitute/health-equity-tracker#1720]
**Describe the bug**
Currently, the `Native Hawaiian/ Pacific Islander (Non-Hispanic)` and `American Indian/ Alaska Native (Non-Hispanic)` races are not included on our methodology page's examples of hispanic/non-hispanic races. We always strive to include small demographic groups on the tracker and those two racial groups should be included when we update to include a definitions of races

The section of the methodology in question was not designed as a glossary to explain the races, but as a list of examples to help users understand Hispanic inclusive versus Non-Hispanic races. However, it's very confusing and since we DON'T have a glossary yet, this has become the de facto race terminology glossary. It's lacking MANY race/eth combos, and we should address the above original concerns as we redesign our #1706 

**To Reproduce**
1. Go to https://healthequitytracker.org/methodology
2. Scroll down to the bottom and look at the `What do the race/ethnicity groups mean?` sections
3. See that AIAN and NHPI are not included

**Expected behavior**
As a user of the site curious about what the race/ethnicity groups mean I can 
1. Go to https://healthequitytracker.org/methodology
2. Scroll down to the bottom and look at the `What do the race/ethnicity groups mean?` sections
3. I can see a definition for `Native Hawaiian/ Pacific Islander (Non-Hispanic)`
4. I can see a definition for `American Indian/ Alaska Native (Non-Hispanic)`

**Screenshots**

<img width="955" alt="Screen Shot 2022-07-27 at 2 34 05 PM" src="https://user-images.githubusercontent.com/3689026/181346846-154a8227-0bf8-4ab5-9315-2d9e700c72c7.png">

**Additional context**

Make sure to get an approval of the definitions from JC or Nelson

**Comment by jgonzalezmsm** [comment]
Please add definitions:

**American Indian and Alaska Native:** A person having origins in any of the original peoples of North and South America (including Central America) and who maintains tribal affiliation or community attachment.  

**Native Hawaiian and Pacific Islander:** A person having origins in any of the original peoples of Hawaii, Guam, Samoa, or other Pacific Islands. 

@joshzarrabi  - can you confirm from the data - it seems we should change  **Native Hawaiian and Pacific Islander:**  to **Native Hawaiian _or Other_ Pacific Islander:** 

full writeup here: https://docs.google.com/document/d/1It_2wpMKUcT2jjROT0U_JoY3SI77irLmSN3q_DJk9ok/edit#

**Comment by jgonzalezmsm** [comment]
Change methodology text:

> _We include a few example groups and definitions below._ Note that the complete definition of a race/ethnicity can only be understood in the context of a particular dataset and how it classifies race/ethnicity (e.g. the presence of "Other" within a dataset changes who might be classified as "Asian" vs "Other").

to

> _We provide a list of race/ethnicity groups found on the Health Equity Tracker and definitions below._ Note that the complete definition of a race/ethnicity can only be understood in the context of a particular dataset and how it classifies race/ethnicity (e.g. the presence of "Other" within a dataset changes who might be classified as "Asian" vs "Other").
