### ISSUE TITLE
Scroll position slightly off for really long madlibs

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1753]
**Describe the bug**
Examples of problems when sticking madlib header contains really long conditions / place names and needs more vertical space; the scrolling is a little off. This is a pretty rare edge case that doesn't break anything just doesn't look as spiffy so deprioritizing this fix. 

**To Reproduce**
1. Go to `/exploredata?mls=1.substance-3.02198&mlp=disparity&dt1=covid_hospitalizations&demo=race_and_ethnicity&dt2=covid_hospitalizations`

**Expected behavior**
Scroll position and menu placement should be dynamically calculated off the header height, to keep it looking pretty. 

**Screenshots**
<img width="1051" alt="Screen Shot 2022-08-16 at 9 46 10 AM" src="https://user-images.githubusercontent.com/41567007/184922678-8c7de625-0d50-48f7-964c-29a833b86307.png">
<img width="1051" alt="Screen Shot 2022-08-16 at 9 45 47 AM" src="https://user-images.githubusercontent.com/41567007/184922668-b558cf37-7dc9-43a5-85d8-7e112db8d5d7.png">

**Comment by jgonzalezmsm** [comment]
agree with your prioritization on this - work as time allows
