### ISSUE TITLE
Figure out how to calculate `pct_shares` for AHR conditions

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#1786]
**Describe the bug**

Previous to #1792  many pct_share values displayed for AHR sum not to 100%. They are now nulled until we figure out how to proceed.

**Expected behavior**
We expect pct_shares to sum to 100% *ONLY IF* we are using demographic groups that cover the entire population. There are quite a few times when this is not the case:
- Hispanic-inclusive race groups (hispanic people identifying as a particular race could be double counted)
- Conditions where we only have data for some of the groups but there may be cases occurring outside of those groups. For example VOTER PARTICIPATION is lacking by race 100k values for NHPI, AIAN, 2+, and Unrepresented. Can we detect this by comparing our inferred "All" estimated total with the sum of each group's estimated total? 

Additionally, our calculations may require INTERSECTIONAL population figures to calculate accurately. Previously we were taking AHR's GROUP 100K and estimating the total case count using that group's population. However, many of the conditions from AHR only measure a subset of the population, meaning to proceed this way we would likely need to ensure the population figure matches the exact demographic breakdown. This might not be possible for conditions. 

### AHR rate denominators:

- "Chronic Obstructive Pulmonary Disease": adults 
- "Diabetes": adults
- "Frequent Mental Distress": adults
- "Depression": adults
- "Excessive Drinking": adults
- "Non-medical Drug Use": adults
- "Illicit Opioid Use": adults
- "Non-medical Use of Prescription Opioids": adults
- "Asthma": adults
- "Cardiovascular Diseases": adults
- "Chronic Kidney Disease": adults
- "Avoided Care Due to Cost": adults
- "Suicide": population (All ages? or only 15+? no group presented for Ages 0-14)
- "Preventable Hospitalizations": Medicare beneficiaries ages 18 and older enrolled in the fee-for-service program
- "Voter Participation": U.S. citizens ages 18 and older. ([original Census tables 4b, 4c](https://www.census.gov/data/tables/time-series/demo/voting-and-registration/p20-585.html) I think)

**More Info**

**To Do**
- [x] hide current pct_share metrics that we can't be confident in
- [x] reach out to AHR and determine best path forward (matching their exact population source?)
- [ ] implement new method for determining `raw count` and thereby `pct_share`
- [ ] add some type of testing to all sources using non-overlapping demographic groups that ensures pct_share metrics sum to 100% (with some level of tolerance for rounding errors) #1805

**Comment by joshzarrabi** [comment]
According to this it looks like they are using the ACS microdata? https://www.americashealthrankings.org/learn/reports/2021-disparities-report/appendix-data-sources

Which would explain a discrepancy, I am surprised it is so large for national data though.

**Comment by benhammondmusic** [comment]
Removed all AHR pct_share metrics in #1792 

Still need to figure out if/how we can infer the raw count of AHR topic to then calculate and display the pct_share metrics. Ideas include:
- using the exact same population source as AHR to reverse engineer numbers using our current strategy
- summing the individual race/age/sex group raw counts to make the "All" count, rather than inferring it from the "All" 100k. Unclear if this is even statistically appropriate
