### ISSUE TITLE
resolve DNS issues

### ISSUE THREAD

**Issue by slagathorr** [SatcherInstitute/health-equity-tracker#185]
Currently the domain name registrar has Netlify (via NS1) as the authoritative source for DNS translation. The healthequitytracker.org domain is currently registered by Google Domains through MSM, and we need to restore the Google Domains DNS servers as the authoritative source so we can point them to the Cloud Run frontend services, and eventually to a GCLB.

**Comment by aaronsn** [comment]
This is done, right?

**Comment by slagathorr** [comment]
Yup, the GCLB is in a separate issue so we can close this out!
