### ISSUE TITLE
Swap FIPs County source

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#198]
Need to swap the source from which we got County FIPs information:
https://github.com/SatcherInstitute/het-frontend/blob/50f1cfca97e368d6105b4089d4120cfef02894e9/app/src/utils/madlib/Fips.ts#L119

We'll also want to make sure there aren't any "Unknown" values

**Comment by vanshkumar** [comment]
This is covered by #136
