### ISSUE TITLE
Territory polygons for Vega Chloropleth

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#210]
If we keep chloropleth maps, we're missing the territories. We need to find polygon data

**Comment by katattack** [comment]
FYI: https://github.com/stamen/geo-albers-usa-territories.

**Comment by katattack** [comment]
Also relevant: https://github.com/d3/d3-geo/issues/152

**Comment by benhammondmusic** [comment]
Closed as we have implemented a solution where territories are displayed as circles on the national map and as their own shapes on local maps
