### ISSUE TITLE
Unrepresented footer should only appear on PrEP, not other HIV topics

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#2106]
**Describe the bug**
Footer is present on all HIV topics

**Expected behavior**
The unrepresented race is only used by PrEP, so the footer should only appear on that topic

**Screenshots**
<img width="1143" alt="Screen Shot 2023-04-02 at 10 49 31 PM" src="https://user-images.githubusercontent.com/41567007/229414552-e7f25257-45b8-4fbf-8aa5-fcdff3401fdf.png">

**Comment by eriwarr** [comment]
This was resolved in PR #2111.
