### ISSUE TITLE
Better handling of missing data

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#213]
- more consistent UI indicators for missing data
- handling for different types of missing data scenarios (eg data source is incomplete vs we don't have a dataset that covers that breakdown vs we haven't yet ingested this data vs this dataset doesn't exist)
- make sure the code is abstracted so we aren't hard-coding any missing data checks

**Comment by benhammondmusic** [comment]
@jgonzalezmsm can we close this issue? Seems like the MISSING DATA issue is addressed well in the current app, and any improvements will be a natural part of the ongoing development, not a specific issue per se

**Comment by jgonzalezmsm** [comment]
Yeah i think this is outdated. Let's close it and if anything new comes up we would create a more specific issue. Thank you!
