### ISSUE TITLE
Bug: Fix nav bar tabs

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#215]
Clicking on button but not the text doesn't change the tab

**Comment by aaronsn** [comment]
Per offline discussion: I think swapping the link to be outside the button may fix this: https://github.com/SatcherInstitute/health-equity-tracker/blob/e4a1e35737134e1f8bcde1409fd23419dad3fd3e/frontend/src/App.tsx#L93

The buttons here work as intended: https://github.com/SatcherInstitute/health-equity-tracker/blob/dcf8468e9e4f024953f6739f94a3293b7cca2163/frontend/src/pages/Landing/LandingPage.tsx#L35
