### ISSUE TITLE
UI font

### ISSUE THREAD

**Issue by achipham** [SatcherInstitute/health-equity-tracker#222]
Change headlines to: DM Sans (https://fonts.google.com/specimen/DM+Sans?query=dm+san)

Change body copy and links to: Inter (https://fonts.google.com/specimen/Inter?query=inter)

**Comment by achipham** [comment]
ON STATIC LANDING PAGES:
Headlines: Taviraj
Body: Inter

ON DATA DASHBOARD:
Headlines: DM Sans
Body: Inter

**Comment by efregoso** [comment]
Completion time estimate: < 1 day
