### ISSUE TITLE
Look into whether we need react-helmet and if so, set it up

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#224]
Chris mentioned this could be valuable for managing the <head> component, if we need any dynamic changes to it, eg updating the <title> element to the current page.

**Comment by benhammondmusic** [comment]
Throughout the app, the sub pages and tabs are setting `<title>...</title>` inside the return statement of the component. This results in the React adding a title tag inside the <body> of the HTML, but to be valid HTML title must be set inside the <head>. 

All browsers seem to handle this despite being invalid, but we should update this to do it properly as not every browsing device will necessarily handle this invalid usage. Helmet is mentioned above, but might be easier to simply create a useTitle hook and implement throughout the app.

This could potentially help with #1055
