### ISSUE TITLE
Look into visual regression testing or other ways to avoid breaking the frontend

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#226]
Unit tests for frontends can be a high maintenance cost and often don't provide good coverage anyway. We might want to look into visual regression testing, where we have a pre-submit rule that automatically diffs site images before and after and shows the difference. There might be other alternatives to this that accomplish a similar thing

**Comment by benhammondmusic** [comment]
We have basic e2e testing with Playwright now; this could be extended to included some visual regression testing
