### ISSUE TITLE
need to improve 404 

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#227]
- [ ] a nicer experience than "Page Not Found", for example suggesting pages to visit or leaving info about SHLI
- [ ] should we return a real 404 response code rather than a 200 (?)

**Comment by benhammondmusic** [comment]
![image](https://user-images.githubusercontent.com/41567007/143377736-0cc98dd8-874a-42f9-8147-69476abe3744.jpeg)
