### ISSUE TITLE
Button state enhancement for Rates over time card

### ISSUE THREAD

**Issue by kccrtv** [SatcherInstitute/health-equity-tracker#2278]
## Is your feature request related to a problem? Please describe.
Users may be having an inaccurate understanding of the button's functionality when it is in an inactive state. In the screenshot, the data being shown is those from "All Groups." As such, the `Show all groups` button should be in an active, focused state instead of as disabled and non-clickable. Subsequently, the `Show highest/lowest averages` should be in a temporary, inactive state, but as such clearly communicates to users that the button can become active under certain conditions or user interactions.
<img width="1072" alt="Screenshot 2023-07-12 at 1 44 42 PM" src="https://github.com/SatcherInstitute/health-equity-tracker/assets/67879386/c29c96b2-bcfd-4ee8-925f-f683ab98300a">

## Describe the solution you'd like
Modify the existing button component to replace the current "disabled-state" with an active-state and the current "active-state" to an inactive-state to accurately reflect the button's functionality. This change will help avoid confusion and improve the user experience by providing clear visual cues regarding button availability and interactivity.

## Additional context / screenshots
By enhancing the button states, we aim to better align with user expectations and industry best practices. This change will contribute to a more intuitive interface and enhance the overall usability of the project.

**Comment by benhammondmusic** [comment]
Once we have report-wide "highlighted race group(s)" (which we sort of already do from the map card, it's encoded in the URL params) we could even add another button that auto-selected the highlighted groups.
