### ISSUE TITLE
Better highlighting for nav bar

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#228]
- More clearly differentiate the button highlight color from the app bar color
- Show the currently viewed page in a different color to indicate where the user currently is

**Comment by aaronsn** [comment]
This can probably be addressed as part of #292

**Comment by aaronsn** [comment]
Did Chi say that the highlighting is good as-is? It seems very unusual to have a nav bar that doesn't highlight the background of buttons when hovered over. That's what almost every website does. The links don't really seem like buttons at the moment.

**Comment by kkatzen** [comment]
Issue of the nav bar not being buttons is tracked in issue #709
Is fixing #709 sufficient to resolve this issue?

**Comment by aaronsn** [comment]
I guess it depends on the CSS the button uses, but probably it's not hard to do - I'm sure the functionality is built into the material-ui Button component
