### ISSUE TITLE
remove Deploying your own instance with terraform link in README

### ISSUE THREAD

**Issue by kccrtv** [SatcherInstitute/health-equity-tracker#2284]
**Describe the bug**
In the README.md, line 256 has a [link for "Deploying your own instance with terraform"](https://github.com/SatcherInstitute/health-equity-tracker#Deploying-your-own-instance-with-terraform) that does not go anywhere within the README.

**To Reproduce**
1. Go to 'README.md'
2. Scroll down to line 254
3. Alternatively, you can jump to section: [Running the Frontend Server in your own GCP project](https://github.com/SatcherInstitute/health-equity-tracker#running-the-frontend-server-in-your-own-gcp-project)

**Expected behavior**
The link should anchor the README to the corresponding header, but it could have been deleted at some point.

**Screenshots**
![Screenshot 2023-07-26 at 1 25 48 PM](https://github.com/SatcherInstitute/health-equity-tracker/assets/67879386/01496f9f-7840-4474-a1bd-4e400574f95c)

**Device (please complete the following information):**
 - Device: Macbook Pro
 - OS: Ventura 13.4.1
 - Browser: Firefox
 - Version 115.0.2

**Comment by benhammondmusic** [comment]
@kccrtv it looks like in our code it used a capital `D` in the word `deploying-`, but for the link to work it needs to be lower-cased. i confirmed that this link is working `https://github.com/SatcherInstitute/health-equity-tracker#deploying-your-own-instance-with-terraform`

Want to make your first PR and make this fix? 🟩 🟩 🟩 🟩
