### ISSUE TITLE
Migrate download button to do server-side downloads

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#234]
I looked into this a bit, seems like downloading files in the browser is a bit of a mess with incomplete browser support for different mechanisms. Need to investigate more but I think there are roughly two approaches:
- Server-side - Add `Content-Disposition: attachment; filename="<name.csv>"` headers to the response, and then just make a link to it from the client. Depending on content type, we may need to use the "download" attribute to ensure it downloads rather than opens in a new tab. The download attribute ensures it actually downloads, but isn't supported in IE.
- Client-side - make fetch for table data and programmatically add download link to the DOM and trigger a click, providing the in-memory data to the link. This is a bit hacky but has the advantage of being able to use the same API as getting the data directly.

The server-side approach seems better generally. I think this will require updating the API to have the client specify whether it's for download or not, and the server then provides the appropriate response headers.

**Comment by jenniebrown** [comment]
The data server currently adds the 'Content-Disposition': 'attachment' header to all responses. Are there any other changes that need to be made on the server side?

**Comment by aaronsn** [comment]
I don't think so! Just needs to be updated on the client side as far as I can tell

**Comment by aaronsn** [comment]
Actually, decided to not do the server-side downloads as it was causing UI issues, and the download performance works well enough for all existing datasets.
