### ISSUE TITLE
Data server doesn't add CORS headers to all requests

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#238]
The metadata request is missing CORS headers. Also, if the dataset isn't found it's missing CORS headers.

The data server is simple enough that we could definitely manually add the headers for every response, but using a Flask extension like https://flask-cors.readthedocs.io/en/latest/ is probably the better way to do it so it is guaranteed to happen for all requests.

**Comment by jenniebrown** [comment]
Do we want to allow CORS for all resources and from all domains?

**Comment by aaronsn** [comment]
We may want to customize this in the future, but as of right now I'd say it should allow CORS for all resources/all domains.
