### ISSUE TITLE
Determine supported browser versions and whether we need to set up additional polyfills for older browsers

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#240]
[create-react-app documentation](https://create-react-app.dev/docs/supported-browsers-features/) is a bit confusing on this point. It says
> The browserslist configuration controls the outputted JavaScript so that the emitted code will be compatible with the browsers specified

but it also says
> Note that this does not include polyfills automatically for you. You will still need to polyfill language features (see above) as needed based on the browsers you are supporting.

... which sounds contradictory to me. One thing is clear, IE 11 and below require polyfills if we want to support that. This may come with the tradeoff of a bigger binary/slower code.

Also, the default config in `package.json` is
```
"production": [
    ">0.2%",
    "not dead",
    "not op_mini all"
],
```
I think the first line means browser versions that have >0.2% usage. Not sure what the other two lines are or if these lines are treated as a union or intersection.

AIs here:
1. Investigate how create-react-app builds work to clarify what browsers it supports out of the box without additional polyfills
2. Determine what browsers we're currently supporting with the default config, and whether we want to change the config to support older browsers (this likely requires product input).
3. Determine whether we need any polyfills based on 1 and 2.

This is not time sensitive as it doesn't affect development. However we should avoid using experimental/non-standard features.

**Comment by vanshkumar** [comment]
Larry is going to do an inventory to see how much of this, if any, we need to do before launch
