### ISSUE TITLE
Frontend error handling and logging

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#244]
Audit frontend code for error paths and ensure errors are A) caught, B) handled gracefully by the UI, C) reported to the server, and D) tracked somewhere on the server along with server errors.

**Comment by aaronsn** [comment]
Now that we have our own frontend server, I think the best way to do this is just send a custom request to our frontend server and have the server log it. This requires no libraries and is pretty straightforward. The frontend already has a logger class that's being used and the environment variables are set up for different environments: https://github.com/SatcherInstitute/health-equity-tracker/blob/897e88c590f20481a7b2bbc2fc35ad321cea752a/frontend/src/utils/Logger.ts#L27

It just needs to have the implementation changed to send the error data to the server. The server will need to add a new endpoint:
https://github.com/SatcherInstitute/health-equity-tracker/blob/master/frontend_server/server.js
That handles the error reports and logs them using a Cloud Run library: https://github.com/SatcherInstitute/health-equity-tracker/issues/29#issuecomment-755546166

**Comment by vanshkumar** [comment]
Moving to backlog for now as per discussion, we should figure this out soon after launch though
