### ISSUE TITLE
Data server request reliability requirements

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#248]
- Make sure retries happen with backoff or user interaction only, not automatically over and over
- Make sure datasets are refreshed periodically, so long-lived clients don't cause out-of-date frontends
- Handling for status codes on the frontend - determine which status codes allow retries and whether we want logging for certain status codes
- Potentially want a max size on the dataset cache so we don't hog memory

**Comment by vanshkumar** [comment]
Closing as per discussion, good enough for launch
