### ISSUE TITLE
SEO (meta data per page using Helmet, etc)

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#250]
(such as putting more metadata into the html head)

**Comment by vanshkumar** [comment]
Do you mind expanding on what this issue is exactly, Aaron?

**Comment by aaronsn** [comment]
I'm not an expert on this but I believe it mostly involves changing invisible site content to improve google search results. So for example, we can include key-words related to the site or mission or MSM so that when people search for related things, our site comes up as a top result. It also may help to link to it from SHLI/MSM sites or from partner sites
