### ISSUE TITLE
Address frontend performance issues

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#251]
https://github.com/SatcherInstitute/het-frontend/issues/124 should help with this. Once that's done, we can have the variable API optimize stuff like filtering the datasets down before doing further processing.

We also will need to keep an eye out for operations that are slow and add preaggregations/prefilters on the backend. For example, a large county-level dataset can be aggregated to the state level on the backend, or joined with ACS on the backend, or chunked into one file per state.

Other things we may want to do:
- improved caching on the frontend (I have a basic implementation but it needs work)
- using an index in data-forge
- setTimeout(0) before doing data processing. This is a very minor thing but at least allows the UI thread to yield before doing the processing, makes the UI look less laggy because the user's interaction is allowed to finish

I also investigated using a web worker to asynchronously process the datasets. This would almost certainly address UI jank. However, web workers don't play super well with a SPA with create-react-app and typescript, so I don't think we should go this route.

**Comment by aaronsn** [comment]
Note from offline discussions: as we add more options to the MetricQuery, the caching gets worse. I'm going to work on seeing if we can get some amount of intermediate caching so that if two MetricQueries rely on the same underlying dataset or query, they won't redo the same work.

**Comment by aaronsn** [comment]
Discussed with Krista, here are the three things I'm working on to improve performance:
1. Fix a bug where if you simultaneously request the same dataset from different cards, the dataset starts loading multiple times rather than just once.
2. Use the `getDependentDatasets` method specified in #283 to only load the datasets actually needed to respond to the query rather than all datasets used by the VariableProvider
3. Support intermediate caching of query results for similar queries. For example, if two queries are identical except for a filter, we can cache a version of the query that doesn't have the filter, and then reuse the result for both.

Doing this is going to require some refactoring, I'm working on making a new `DatasetCache` class that better supports these use cases.

**Comment by aaronsn** [comment]
The first two things are done, the intermediate caching part is technically supported but would need some work to actually do. I don't know if we'll need it though, and it adds complexity, so for now I'd say let's hold off.

**Comment by aaronsn** [comment]
Leaving this open to re-assess once we have more datasets in use

**Comment by vanshkumar** [comment]
Moving performance issues to backlog as perf seems fine for launch
