### ISSUE TITLE
Map Legends - determine feasibility of displaying min/max instead of calculated breakpoints

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#257]
Can we have the boundaries of the map's legend be round numbers instead of 3,126, 6,624

**Comment by efregoso** [comment]
Completion time estimate: < 2 days

**Comment by kkatzen** [comment]
I'm not even sure if we can do this for legends if we're using quantize/quantile scales? Isn't it the point that the values are calculated? We could look into the ticks on the bar charts though

**Comment by kkatzen** [comment]
We discussed this in yesterday's eng sync- Product was going to spend some more time thinking about what their ideal would be. Eng can look into how easy it is to just display "min" "max" on the current legend in the meantime.

**Comment by adams314** [comment]
I think showing min/max is the best suggestion to date. Please advise if this is possible/practical

**Comment by kkatzen** [comment]
So I don't think this is a trivial change... we may still be able to hack it somehow... how important is this?

**Comment by adams314** [comment]
Not super important...moving it to the backlog and we can revisit later

**Comment by benhammondmusic** [comment]
Closing; dealing with funky legends in #1575
