### ISSUE TITLE
Future improvements for ACS data ingestion

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#26]
- Figure out how to handle updating the url. It's currently hard-coded to 2018 which is the most recent 5-year ACS dataset.
- We should register a developer key, which gives you a much higher quota. This may not be relevant since we'd likely be under the quota, but doesn't hurt to register one.

Done:
- Confirm which census dataset to use for population breakdowns: currently using the 5-year ACS dataset but there's also a 1-year and 3-year dataset and I think you can also get population breakdowns from the actual 10-year census.
- Consider migrating to another source. BigQuery public datasets include census data which is convenient since it's already in BigQuery, though the documentation on the schemas is pretty poor from what I've seen. Another option is using [DataCommons](https://docs.datacommons.org/tutorials.html) which has a pretty powerful/expressive python API

**Comment by katattack** [comment]
For question 1, we should use the 5-year ACS (2014-2018 is the most recent one, 2015-2019 will be released in Dec) given that we want to use county data: https://www.census.gov/programs-surveys/acs/guidance/estimates.html.
