### ISSUE TITLE
Frontend: Refactor DatasetMetadata for download and data catalog requirements

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#264]
acs_population-by_race_state_std and acs_population-by_age_state are unique dataset IDs.

This means they would show up as separate items in the data catalog. We would like them to be in the same card instead

see FakeMetadataMap

**Comment by aaronsn** [comment]
One note on this - we decided that only datasets with the suffix "_std" will be surfaced in the data downloads page (others are aggregations that are based on the "_std" datasets, so users can reproduce the same data with the underlying "_std" version). A future feature request could be to offer downloads of different variants in the download cards, but this would require building out a UI for displaying the different variants and I believe is out of scope for MVP.

Also, we should revisit the format of the FakeMetadataMap now that a few developments have evolved:
1. We have a better sense of what the requirements are for the explore data and data downloads page, and the frontend architecture has started to solidify. This may make some of the metadata unnecessary. For example, do we need to list the fields for every dataset? We don't really use them in the downloads page, and this seems reasonable to hard-code into the VariableProviders.
2. It's looking unlikely we'll get a full end-to-end metadata implementation for launch, and we may need to hard-code some static metadata similar to the MetricConfig. Given that, it seems infeasible to maintain such granular metadata in the FakeMetadataMap, when most of it is unused, especially for those that won't be in the downloads page. In fact, arguably we don't even need to list any of the aggregated datasets in the metadata map at all.

My recommendation is to split out the static from dynamic metadata. Slim down the static metadata to the minimal set we need for current features, and scope down backend metadata requirements to only dynamic metadata (I think last update time is the only dynamic metadata at time of writing).

What do you think?

**Comment by kkatzen** [comment]
1. Sync with product to figure out if datasets with different standardized versions (such as ACS race and ACS age) should be the same card or not.
2. Migrate download button to go straight from the server instead of in the frontend to decouple its use of DatasetMetadata so we can update DatasetMetadata #234 
3. Change DatasetMetadata to only take update_time from the backend
export interface DatasetMetadata {
  readonly id: string;
  readonly update_time: string;
}
4. Create a static config in the frontend that will provide the rest of the DatasetMetadata according to product specifications
5. Audit frontend usage of Metadata to make sure it makes sense with this new framework
6. Ensure documentation is updated so that all these static configs are updated appropriately

**Comment by aaronsn** [comment]
One other thing - if we do decide to offer different variations of the same dataset for download, we will need to change the exporter to export aggregations as CSVs also (currently it only exports the base tables as CSVs).

**Comment by kkatzen** [comment]
Note that this logic also impacts the Card Footer citations

**Comment by aaronsn** [comment]
From frontend/UX sync - leaning towards having one card per source (eg ACS population), and if there are multiple versions from that source then the download button would show a popup with the option to choose your specific version.

Still needs to be confirmed though, we didn't entirely settle this

**Comment by kkatzen** [comment]
Data catalog will have one card per data source and clicking download will open a pop up dialog that will, for MVP, list all files available for download. Downloads only happen from this popup.
