### ISSUE TITLE
Legend header shouldn't center on smaller screens

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#2692]
**Describe the bug**

On smaller screens the legend header centers. This is incorrect and probably was a bug from #2661 

**Expected behavior**
The legend header should be left aligned above the legend as shown below. If we wnat to change the design here maybe we could, centering both the header AND the legend items on smaller screens. but i want this to be intentional rather than accidental

**Screenshots**

BEFORE (CORRECT)

<img width="586" alt="Screenshot 2023-12-29 at 8 31 35 PM" src="https://github.com/SatcherInstitute/health-equity-tracker/assets/41567007/a06f23be-df26-404a-a9a0-e3882918d14d">

AFTER (INCORRECT)

<img width="586" alt="Screenshot 2023-12-29 at 8 29 11 PM" src="https://github.com/SatcherInstitute/health-equity-tracker/assets/41567007/2fc41c1e-d1f0-4e0a-bf3f-3658a89ebbf0">

**Device (please complete the following information):**

**Additional context**

**Comment by PraveenShinde3** [comment]
@benhammondmusic  i don't see the legend header been center aligned for mobile screens, 

page i am referring to : https://healthequitytracker.org/exploredata?mls=1.hiv-3.08&group1=All

am i looking at wrong page 🤔 ?

![image](https://github.com/SatcherInstitute/health-equity-tracker/assets/107350270/cecf5d8b-761c-4392-8f3a-47a73acb4d28)

**Comment by benhammondmusic** [comment]
> @benhammondmusic i don't see the legend header been center aligned for mobile screens,
> 
> page i am referring to : https://healthequitytracker.org/exploredata?mls=1.hiv-3.08&group1=All
> 
> am i looking at wrong page 🤔 ?
> 
> ![image](https://private-user-images.githubusercontent.com/107350270/293446246-cecf5d8b-761c-4392-8f3a-47a73acb4d28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3ODQxNDIsIm5iZiI6MTcxNDc4Mzg0MiwicGF0aCI6Ii8xMDczNTAyNzAvMjkzNDQ2MjQ2LWNlY2Y1ZDhiLTc2MWMtNDM5Mi04ZjNhLTQ3YTczYWNiNGQyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQwMDUwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDFhZWRhYTJkZjFiZjc3NDJlM2I3OGVhMzI2NzhiOGE4YmM0NjEzZTBiYmY3ZWYwNmIyN2E0ZmEyODM0MTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-JR65KEONRHT8LNDSDALhoB6wRO3K7OPIoyLQOW-JXA)

@PraveenShinde3 so sorry I didn't see this comment until now! For me on Chrome on Desktop, with the width set to just below 600 px (just after the legend relocates from its own side bar and slides underneath the map), the legend TITLE is centered, but the div with the legend items is left aligned. On these smaller screens the centered legend title actually looks good I think but maybe the trick is centering the collection of legend items as well
