### ISSUE TITLE
Split prod release for frontend and backend

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#275]
For starters, we're making one prod release for the whole infrastructure. In theory it would be nice to split the frontend deploy from the backend (frontend would probably include the frontend server and the data server, backend would be everything else) so we could roll out/roll back independently.

The big reason to do this is that the frontend and backend have very different iteration cycles since the frontend will probably require more minor UI changes (for example updating "About Us" content). It would be nice to be able to release these UI changes without needing to be sure any in-progress backend work is ready for release.

@mayaspivak

**Comment by aaronsn** [comment]
Tasks required for this:
- split terraform configuration into a backend module and a frontend module
- split the prod deploy workflow into two - each one deploys just the relevant terraform module

**Comment by benhammondmusic** [comment]
Sort of did this by #3008 ; for frontend only changes, we can now cut a new release that doesn't restart need to restart composer. We can also use #2188 and test out changes to the backend code before committing them to `main` by force pushing to `infra-test`

closing this for now
