### ISSUE TITLE
Cloud run development issues

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#28]
Couple things I noticed while getting started with cloud run for the ingestion pipeline:
- logging.info() doesn't show up in the cloud run logs, but logging.warning() does.
- There are seemingly infinite retries on failure that are very spammy. Also, when I ran the household income scheduler, even though it succeeded it was causing lots of retries that the other data sources weren't. I wonder if this is because it took too long to ack (it took much longer than the other ones I tested, around ~40 seconds).

Not sure but one/both of these things may be addressed if we use Airflow?

**Comment by aaronsn** [comment]
@jenniebrown @mayaspivak @ldbnr4 FYI

**Comment by jenniebrown** [comment]
I'm updating the ack deadlines and retry with backoff in my cl to address the spam. I think we should think about how we respond to messages that are not retriable. Right now we NACK a lot of things that are not really retriable and have infinite retries.
