### ISSUE TITLE
Handle multiple data sources per metric

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#283]
Scenario: a single metric comes from multiple data sources. For example, covid cases at the state level come from CTP, covid cases at the county level come from the CDC. Right now, that will result in the card footer showing both of the sources, when only one of them is being used for the current data. This is confusing because the user has no way of telling which data source was actually used for the data they're looking at.

To solve this, we will add a `getDependentDatasets(query: MetricQuery)` method on the VariableProviders that specifies which datasets are required to serve a particular query, and change `variableProviders.getDependentDatasets()` to use that rather than referencing the static list of datasets.

**Comment by kkatzen** [comment]
A reminder regarding the footer:
For MapCard, we request all demographic breakdowns if the "all" toggle (race/age/sex/all) is selected which results in multiple ACS datasets listed. This issue does not address that. #264 should add a static map of consolidate unique dataset IDs (acs_race, acs_age) that point to the same data source (ACS)

**Comment by kkatzen** [comment]
This is no longer needed for the MVP so we'll de-prioritize. It is something we may want in the future, however.

**Comment by benhammondmusic** [comment]
@joshzarrabi was this addressed in your recent vaccine update? Or do we still need to fix the cited sources?
