### ISSUE TITLE
Once methodology launched, condense "About Us" page

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#2831]
Currently, the top level link is to "About Us" and the three tabs are "The Project", "Our Team", and "Contact Us"

After the new methodology hub is live, it will include much of the info the "The Project" tab so that can be deleted

Additionally, we could combine Contact Us and Our Team into a single tab, with the contact info up top and then the team info and pics below.

**Comment by kccrtv** [comment]
can we remove the email address sign up field? i'd rather link our social icons there if possible.

for the _Ethics_ section, can we change the Inter weight from 100 to 400?

on mobile, for the _About the HET_ section, the paragraphs need the same margin as the _Ethics_ section.
