### ISSUE TITLE
Setting Up `GunViolenceProvider.ts`

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#2881]
This provider file will handle the loading of data for gun deaths in the general population (stored in the HET `cdc_wisqars_data` BigQuery resource/tables) and then providing subsets of that data to cards/visualizations as needed using the `MetricQuery` setup

- [x]  Create a new file named `GunViolenceProvider.ts` in the `frontend/data/providers/` directory. Name is "gun violence" in case we expand beyond just deaths in the future
- [x]  Import necessary utilities and types, such as getDataManager for data fetching and various types for type-checking (e.g., Breakdowns, MetricQuery, MetricId).
- [x]  Define a new class that extends VariableProvider. This class will encapsulate all functionality related to your dataset.
- [x]  Initialize the provider with a unique identifier and a list of metric IDs that this provider will handle in the class constructor.
- [x]  Implement the required methods based on the abstract methods in VariableProvider:
    - `getDataSetId`: Determines the correct dataset ID based on the provided breakdowns. The returned DatasetId  will be the same as the BigQuery `data_source` + `-` + BigQuery `table_name`: e.g. `cdc_hiv_data-race_and_ethnicity_state_current-with_age_adjust`
    - `getDataInternal`: Fetches and processes the data according to the metric query, applying filters and returning a MetricQueryResponse.
    - `allowsBreakdowns`: Checks if the requested demographic breakdowns are supported by this provider.
- [x]  Implement any additional utility methods needed for filtering, renaming, or otherwise manipulating the data specific to your dataset.
- [x]  Ensure the provider class is exported correctly so other application parts can utilize it.

**Comment by eriwarr** [comment]
Closing. Resolved in PR #2946.
