### ISSUE TITLE
Updating the MadLibs Configuration for New Gun Violence (Gen Pop)'s Dataset Integration

### ISSUE THREAD

**Issue by kccrtv** [SatcherInstitute/health-equity-tracker#2898]
Due to the multifaceted nature of Gun Violence, it could essentially fit in the categories of `Behavioral Health`, `SDOH`, and/or `PDOH`. However the most fitting category (in this author's opinion) seems to be `SDOH` since gun violence is often influenced by social factors such as poverty, preventable hospitalizations/avoided care, and generally limited access to resources.

- [x] In the `MadLibs.ts` file, update `DROPDOWN_TOPIC_MAP` to add an entry for your dataset, using the Gun Violence (Gen Pop) file's metric name as the key and a descriptive label as the value.
- [x]  Update `SELECTED_DROPDOWN_OVERRIDES` (if necessary): If your dataset requires overriding the default selections in specific contexts (e.g., when it's chosen, another dropdown should default to a specific selection), update or add to this configuration.
- [ ]  Update `CATEGORIES_LIST` (if necessary): Similar to step 1, only update if you've introduced a new category.

**Comment by eriwarr** [comment]
Closing. Resolved in PR https://github.com/SatcherInstitute/health-equity-tracker/pull/2946.

**Comment by eriwarr** [comment]
Closing. Resolved in PR https://github.com/SatcherInstitute/health-equity-tracker/pull/2946.
