### ISSUE TITLE
Updating Metadata Configuration for New Gun Violence (Gen Pop) file's Dataset Integration

### ISSUE THREAD

**Issue by kccrtv** [SatcherInstitute/health-equity-tracker#2899]
- [x] Update `DataSourceId` to include the new source id, i.e. (CDC WISQARS would be ‘cdc_wisqars’)
- [x]  Update `MetadataMap.ts` to include the new Gun Violence dataset by adding a new entry under `dataSourceMetadataMap`. Each entry should provide essential information about the `gun_violence` dataset, including its name, source, geographic coverage, demographic granularity, and a brief description.
- [x]  Update `DatasetMetadata.ts` to include metadata entries for each specific `gun_violence` dataset or file that comprises your new dataset.

**Comment by eriwarr** [comment]
Closing. Resolved in PR https://github.com/SatcherInstitute/health-equity-tracker/pull/2946.
