### ISSUE TITLE
Figure out strategy for error logging/monitoring/alerting

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#29]
Very open-ended task, but includes:
- How are errors monitored/alerted on?
- Standardize severities, eg what constitutes failing a task vs just logging a warning
- Once we do this, audit code and make sure errors are properly handled (I'm guessing for early development we're going to be lax about this)

Airflow might help with this, though the web app will also need to do similar things.

**Comment by slagathorr** [comment]
CC'ing in @jenniebrown @mayaspivak @aaronsn as we all work this out together!

**Comment by slagathorr** [comment]
We have found libraries for [error reporting](https://cloud.google.com/error-reporting/docs/setup/nodejs), and [cloud logging](https://cloud.google.com/logging/docs/reference/libraries#client-libraries-install-nodejs). We are verifying which to use when for errors that are reported by the frontend services.

**Comment by aaronsn** [comment]
From glancing through the docs, I think the error reporting API is simply a wrapper around the logging API that makes the interface simpler/cleaner for error reporting. Since that's the main use case we're currently targeting, we should probably use that.

**Comment by vanshkumar** [comment]
Moving to backlog for now as per discussion, we should figure this out soon after launch though

**Comment by aaronsn** [comment]
Note: #244 is a separate issue for implementation of logging on the frontend. While this issue is more focused on just figuring out what we're doing with logging/monitoring, #244 will require some implementation to make the frontend send error reports to the backend and have those logged using the same system as backend errors
