### ISSUE TITLE
For % of metrics, remove unknowns

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#291]
Currently, in disparity bar chart and table you can see "Unknown" in race listed as it's own bar/row. Percentages calculated include this "Unknown".

Instead, let's remove unknown cases from the denominator such that "% of cases" instead is actually "% of cases in which race was known".

However, we still want a way to get the "Unknown" metric as part of the actual, raw "% of cases"

Are these two cases separate metricIds ? Are they the same metricId but with a different breakdown (similiar "includeTotal" we could have "excludeUnknown"?

**Comment by vanshkumar** [comment]
Assigning myself for now to triage
