### ISSUE TITLE
Update the main site styling

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#292]
Right now we have a temporary landing page I'm going to push to healthequitytracker.org, the idea is for the rest of the site to match that.

- Update the app bar to use the logo
- Update the app bar to be white background and purple text
- Update the theme colors and fonts to match the mocks

I think we need a bit more specification on what the main site will look like - I'm not sure how exactly the temporary landing page styles map to the explore data page or data downloads page.

**Comment by aaronsn** [comment]
@kkatzen FYI

**Comment by vanshkumar** [comment]
This is covered by work on static landing pages that is already in progress
