### ISSUE TITLE
Design for handling data sources changing and avoiding duplicate/redundant data

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#30]
Currently the code is set up to ingest the same data source even if it hasn't changed. This causes duplicate data in BigQuery. This isn't a big deal for now because we have an ingestion_time timestamp so it's easy to just query all rows where `ingestion_time = MAX(ingestion_time)` to avoid duplicates/old data. The upside is it makes ingestion very simple. The downside is it complicates the data and uses unnecessary storage and query costs (time & money).

We should figure out whether to change this strategy. Some things that would need to be thought about if we do:
- how do we detect if the data has changed to prevent ingesting duplicates?
- how do we preserve historical data?

I think avoiding ingesting redundant data in the first place could get complicated as it may vary by data source. One idea I had is to keep the ingestion as is, and then periodically materialize new tables with just the latest data. Then the old data can be cleaned up with a periodic task or automatically with a TTL.

Eg:
`ingest data to GCS bucket  =>  upload from bucket to BigQuery  =>  BigQuery_historical_table  =>  BigQuery_current_data`
BigQuery_historical_table would have duplicate/redundant data and periodically get cleaned up, but BigQuery_current_data would always be the most recent.

**Comment by aaronsn** [comment]
@mayaspivak @slagathorr If I remember correctly, both of you mentioned having opinions on this

**Comment by jenniebrown** [comment]
I think that if we're not going to use ingestion time partitioned tables then my preference would be to use checksums at the GCS level to decide whether or not to continue to upload data. You can compute the md5 or crc32 checksum on data before uploading and check against the checksum of existing data in GCS (if any) to decide whether to upload at that point.

**Comment by slagathorr** [comment]
Ooh. I do like the checksum idea, but might suggest doing that inside of BQ as a scheduled query. If the datasets get larger, it might be faster/cheaper/simpler to just use Dremel's horsepower to perform creating checksums and deduplications in bulk as a single atomic operation. Also means you get the benefits of BQ managing the schedules, capacity, and also provides a built in 7 day window to recover data in case something went wrong.

**Comment by mayaspivak** [comment]
We could do a combination of the two. I think Jenny's suggestion to do it in GCS is best for the datasets we know are updated rarely (e.g. once a year). Pulling those into BQ daily or weekly would be excessive. But we could do the checksum in BQ for datasets we know are updated more frequently.

**Comment by aaronsn** [comment]
I think there's some value in doing it in the same way across datasets for consistency/maintenance (if they're simple enough mechanisms then it's probably fine to have two ways of doing it, but all else considered I'd prefer one way).

**Comment by slagathorr** [comment]
Example query that helps identify/collapse duplicate rows, and how to filter for "latest" rows.

`# Create sample data table.
# California is a late arriving update.
# Delaware has a duplicate.
# Kansas is a non-duplicated non-changing row.
CREATE TEMP TABLE source_data AS ((
  SELECT DATE(2020,1,15) AS ingest_dt, DATE(2020,1,1) as reported_dt, 'California' AS state, '10' AS count)
  UNION ALL (SELECT DATE(2020,2,15), DATE(2020,1,1), 'California', '90') # This is the 'latest' row for California
  UNION ALL (SELECT DATE(2020,10,10), DATE(2020,10,5), 'Delaware', '50') # This is the 'latest' row for Delaware
  UNION ALL (SELECT DATE(2020,10,11), DATE(2020,10,5), 'Delaware', '50')
  UNION ALL (SELECT DATE(2020,11,10), DATE(2020,8,16), 'Kansas', '32')); # This is the 'latest' row for Kansas

# Create a target table with the source table minus duplicates (the second Delaware row).
CREATE TEMP TABLE target_table AS(
  SELECT DISTINCT * EXCEPT(ingest_dt, grp), # Get the original columns EXCEPT ingest_dt
    min(ingest_dt) OVER(PARTITION BY grp) ingest_dt # Get the minimum ingest_dt within a partition of the same JSON group
  FROM (
    SELECT *, # Get all columns.
    REGEXP_REPLACE(TO_JSON_STRING(t), r'"(?:ingest_dt)":.+?[,}]', '') grp # Serialize JSON of all columns EXCEPT ingest_dt
    FROM source_data t
  )
);

# Select only the latest ingest_dt for any given row.
SELECT * EXCEPT (rank)
FROM(
  SELECT *,
  RANK() OVER(PARTITION BY state ORDER BY ingest_dt DESC) rank # Rank each group of rows for a state in descending ingest_dt
  FROM target_table
)
WHERE rank = 1; # Get the top ingest_dt, which is the 'latest' date`

**Comment by slagathorr** [comment]
Also, per https://github.com/SatcherInstitute/health-equity-tracker/issues/103#issuecomment-742036043 we are standardizing with `ingest_ts` for all tables so we can use that to use for identifying duplicate rows.

**Comment by aaronsn** [comment]
Brian, I just realized (maybe I'm misunderstanding the SQL so lmk if this is wrong) - isn't your last query only selecting one row per state because it's partitioning by state? What if there are multiple? For example:

```
ingest_ts, state, age, population
1/10, CA, 0-9, 500000
1/10, CA, 10-19, 600000
1/10, CA, 20-29, 700000
```

Wouldn't this just return one of these rows?

**Comment by slagathorr** [comment]
You're reading that right. One of the things we talked about in the WC is the fact that we have to figure out how to "key" things in order to get the latest one. I'm thinking about how to make it more generic so you don't have to, which is being worked on, but your understanding is correct.

**Comment by aaronsn** [comment]
Could we just skip step 2 of the deduping and rely on the checksum step to avoid having too much redundant data? That would enable a much simpler query where you always just select the latest timestamp. In other words, if any rows in the whole dataset change we'd add all rows again, but if they're all identical the checksum step would skip it. This would be inefficient if it's common for only a few rows to change and datasets are really large. But I wonder if the common case would be acceptable and makes this simpler. Of course, that means relying on the checksum step. Just brainstorming

**Comment by slagathorr** [comment]
The checksum at the file level is applied to everything to tell if the entire dataset is identical. The issue is that if the files are different, and only, for example, 50% of the rows are different and 50% are identical, the checksum doesn't tell you which records are the ones that are different.

So reloading the entire table every time to get around that works so long as it operates under the assumption that every ingest has the entire dataset for every load. Which might be true. The case where that doesn't entirely work is in the scenario where you have a table with 10 months of data, and the current load has data for the last 7 days, of which 3 of those days have updates to historical data. For once a month/year datasets it's not really an issue, but could see that happening for things like daily reported cases, or daily reported hospitalizations, where data trickles in over time.

Unless we pull those datasets so infrequently we don't expect that to change. Which is also another viable solution to it, so long as we're okay with a lag in data. Not sure who makes that call, but it's an option.

**Comment by slagathorr** [comment]
@ldbnr4 It took longer than I hoped, but finally debugged the logic in some BQ Script that will take a table of input data, check it against a base table to see if input rows are updates to previous ones, ignores duplicates, and deflags updated rows and inserts the new ones. I'll document it all out on how the inner guts works, but if you want to give it a whirl, do the following:

1. Run [this query](https://console.cloud.google.com/bigquery?sq=497790152117:940b460df9394b9d8e2c3c4f5377368f) to create sample data (run it anyway so you reset it in case someone else tested it).
2. If you want to take a look at the tables, run ```SELECT * FROM `temporary-sandbox-290223.dedup_test.main_table` ``` and ```SELECT * FROM `temporary-sandbox-290223.dedup_test.ingest_table` ``` to see what the data looks like.
California has an update, and a new row, and a duplicate from history.
Delaware is a duplicate.
Florida is a new row.
3. Test out the function by calling:
```
CALL
  dedup_test.superDeduper(
    '`temporary-sandbox-290223.dedup_test.ingest_table`',
    '`temporary-sandbox-290223.dedup_test.main_table`',
    'ingest_ts',
    'is_latest',
    ['reported_dt', 'cola', 'colb'],
    ['measurement', 'colc']
  );
```
4. Look at the data by running
```
SELECT * FROM `temporary-sandbox-290223.dedup_test.main_table` ORDER BY 4, 5, 3, 2 ASC, 1 DESC
```
In the [definition of the script](https://console.cloud.google.com/bigquery?project=temporary-sandbox-290223&folder=&organizationId=&p=temporary-sandbox-290223&d=dedup_test&r=superDeduper&page=routine), the comments at the top describe what each input parameter is.

Documentation on the actual logic itself is coming, as well as rolling this into the TF deployment, but the script works!

**Comment by slagathorr** [comment]
Finally got around to writing out how the thing actually works.

https://briansuk.medium.com/bigtips-removing-duplicates-while-maintaining-row-history-520f24706d63

**Comment by vanshkumar** [comment]
We decided to go the simpler route (overwrite datasets) until launch & will re-evaluate post launch. See doc for details: https://docs.google.com/document/d/1pC-8z-wxLvEe509AoTPKoTBhgTocJe4HxmmmMJeuq1M/edit?usp=sharing

**Comment by benhammondmusic** [comment]
Keeping this and adding to our “change over time” potential milestone as this may pertain to calculating that information
