### ISSUE TITLE
Frontend changes to support backend race changes

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#307]
ACS & Covid Tracking project are going to split race_and_ethnicity into two columns:
something like:
race_or_ethnicity & reports_ethnicity

In the frontend, we'll use these two columns to create the race_and_ethnicity field (as we currently have it). (API should ultimately be returning same values to the cards)

Additionally, instead of one table for cases, deaths and hospitalizations we will have 3 different tables. Each variable may contain different values for various metadata fields (such as reports_ethnicity)

So the current single dataset feeding into CovidProvider is of the format:
FIPS/race_and_ethnicity/cases/hospitalizations/deaths

And we will now have it turn into 3 datasets of the format:
FIPS/race_or_ethnicity/reports_ethnicity/some_metadata/some_other_metadata/cases
FIPS/race_or_ethnicity/reports_ethnicity/some_metadata/some_other_metadata/deaths
FIPS/race_or_ethnicity/reports_ethnicity/some_metadata/some_other_metadata/hospitalizations

CovidVariable provider will now need to take a MetricQuery in getData() now so we know which datasetId to get since each Metric will now require a different one.
Additionally, we want MetricQueryResponse to have a new attribute returning those metadata fields (reports_ethnicity, some_metadata, some_other_metadata). Metadata fields in MetricQueryResponse can be used as warnings or footnotes on the card. For instance: "Races for NC covid cases does not include hispanic" and "Races for NC deaths does include hispanic"

**Comment by kkatzen** [comment]
Given that we aren't using CTP anymore we're pivoting what we're doing here pre-launch.

Frontend will expect backwards compatibility as far as using the existing "race_and_ethnicity" column. ACS data from backend will now also send "race_includes_hispanic" boolean (https://github.com/SatcherInstitute/health-equity-tracker/issues/339#issuecomment-786762651). This boolean should be added to MetricQueryResponse and available for use in CardWrapper. For datasets that don't provide this value from backend, we'll hardcode it's value for now in each provider.

I'll sync with Chi to figure out how we are displaying this information in the Cards.

**Comment by kkatzen** [comment]
![footnote_v1](https://user-images.githubusercontent.com/6402808/110867189-3a8f7300-827b-11eb-9bba-90c6ef0366ac.png)

**Comment by vanshkumar** [comment]
The BE changes to add separate race and ethnicity columns are done. Over time post-launch, we should move the FE to start using these new columns. Moving to backlog

**Comment by aaronsn** [comment]
A note for whoever ends up picking this up later

In order to migrate away from using race_and_ethnicity, I think we'd have to either:
1. Port the [Race enum](https://github.com/SatcherInstitute/health-equity-tracker/blob/e289a46a2a0aae8bef2e441047fd873288adfe72/python/ingestion/standardized_columns.py#L62) functionality to the frontend so it can convert race_category_id into human-readable labels, or
2. If we need to use the same mapping from `race_category_id => (race, race_and_ethnicity, race_includes_hispanic)` on both the frontend and backend, we could export the race metadata as a table and request that from the frontend.
