### ISSUE TITLE
Cache the Service Account token in the frontend server

### ISSUE THREAD

**Issue by mayaspivak** [SatcherInstitute/health-equity-tracker#319]
The token is used to make requests to the private data server. It is currently fetched from the metadata server on every request. Instead it could be cached and only refreshed when it has expired. Some documentation here: https://cloud.google.com/run/docs/authenticating/service-to-service#nodejs

**Comment by aaronsn** [comment]
Adding this to the MVP infra milestone for now, until we can assess performance better on the frontend. Likely we can skip doing this though, assuming it's not a big performance overhead

**Comment by vanshkumar** [comment]
Moving performance issues to backlog as perf seems fine for launch
