### ISSUE TITLE
Setup `MaternalHealthProvider.ts`

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#3304]
## Setting Up a New Data Provider

- [x]  Create a new file named `[YourDatasetName]Provider.ts` in the `frontend/data/providers/` directory.
- [x]  Define a new class that extends VariableProvider. This class will encapsulate all functionality related to your dataset.
- [x]  Initialize the provider with a unique identifier and a list of metric IDs that this provider will handle in the class constructor. These metric ids will be the column names for float data from the backend source, like `{condition}_per_100k` and `{condition}_estimated_total`
- [x]  Implement the required methods based on the abstract methods in VariableProvider:
    - `getDataSetId`: Determines the correct dataset ID based on the provided breakdowns. The returned `DatasetId`  will be the same as the BigQuery `data_source`   + `-`  + BigQuery `table_name`  : e.g. `cdc_hiv_data-sex_state_current`
    - `getDataInternal`: Fetches and processes the data according to the metric query, applying filters and returning a MetricQueryResponse.
    - `allowsBreakdowns`: Checks if the requested demographic breakdowns are supported by this provider.
- [x]  Implement any additional utility methods needed for filtering, renaming, or otherwise manipulating the data specific to your dataset.
- [x]  Ensure your editor has imported necessary utilities and types, such as getDataManager for data fetching and various types for type-checking (e.g., Breakdowns, MetricQuery, MetricId).
- [x]  Ensure the provider class is exported correctly so other application parts can utilize it.
- [x]  Import new provider into `VariableProviderMap.ts`

**Comment by JDemlow** [comment]
I am receiving some TypeScript errors but they don't always appear in VSCode. I'm going to push my code and hopefully, the errors won't persist. I may not know enough about TypeScript yet to be able to double-check myself

**Comment by JDemlow** [comment]
Looks like some of the merge tests failed. I'll try to go through the TS errors and learn as I go

**Comment by benhammondmusic** [comment]
Usually VSCode only runs its type checking stuff against the open files; however some changes are definitely rippling down and affecting other files that you haven't opened in VSCode. for this type of stuff where the PR (CI) tests are failing, the best is to try to figure out exactly what was running on CI to cause the failure and then replicate that. So here for instance, if you look at the failed step on the github action it was running the "build" command, which in turn was running the type checker `tsc`.

<img width="1383" alt="Screenshot 2024-05-21 at 10 54 39 AM" src="https://github.com/SatcherInstitute/health-equity-tracker/assets/41567007/0a07cd65-a402-4a3f-9e7c-1330b565fef6">

We should probably add a `tsc` check to our pre-commit step; I think we used to have it and I forgot to put it back in when I redid everything. but for now, you can either manually run `tsc` on your CLI in frontend/ and it should generate all these same errors, or usually I just look at which files are causing issues on the error log, and open them in VSCode, and then vscode will highlight the errors
