### ISSUE TITLE
ACS Population: changes needed to accommodate deduping

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#341]
Three things:
1. Standardization logic should add a "year" column to differentiate each version of ACS. This can easily be extracted from the API url, or passed in as an additional argument via airflow
2. Provide the deduper with the uniquely identifying columns so it knows how to dedupe (or skip the deduper altogether since we don't expect the data for the same year to change. Not sure which is better)
3. Switch to using the "latest" table for aggregations (see https://github.com/SatcherInstitute/health-equity-tracker/issues/328 for context)

**Comment by vanshkumar** [comment]
Moving this to backlog as we are no longer doing dedupe
