### ISSUE TITLE
ACS Population: additional categories needed

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#342]
- For race, we need new categories to support CTP data: Asian/Pacific islander combined, and Indigenous.
- For age, we probably need more buckets to support upcoming datasets like BRFSS and health insurance
- For age and sex we need to add a "Total" value

These can probably all happen in either the standardization or aggregation steps. There are tradeoffs either way

**Comment by vanshkumar** [comment]
Moving to backlog as I don't think this is needed for launch
