### ISSUE TITLE
Validate metadata for Covid Tracking Project

### ISSUE THREAD

**Issue by jenniebrown** [SatcherInstitute/health-equity-tracker#344]
There are some discrepancies between the metadata file we received and the published data on the CTP CRDT website. We should make sure our metadata is correct, decide how to handle inconsistencies, and document any edits we need to make.

**Comment by jenniebrown** [comment]
We have reached out to CTP to ask about discrepancies in the metadata, but haven't heard back yet. The known discrepancies and open questions are described as follows:

1. There are a few mismatches between the race & ethnicity combined vs. separate columns for cases and deaths in the metadata spreadsheet:

GA: Website card, dashboard, and data = combined. Metadata = separate.
MS: Website card, dashboard, and data = combined. Metadata = separate.
MN: Website card, dashboard, and data = separate. Metadata = combined.

For WY, everything matches except for the website card:
WY: Website dashboard, data, and metadata = combined. Website card = separate.

2. WY's website card is also saying right now that 0% of cases report race and ethnicity. So maybe WY's card is having a separate, unrelated issue?

3. NC and SC don't match between the website and the metadata spreadsheet for API. Both are listed as "Yes" for API-cases in the spreadsheet but their website cards show Asian on its own without Pacific Islander, and the dashboard has the note that NC/SC don't say if Pacific Islander is included in Other. In related news, AL handles Pacific Islander in the same way, and it has API-cases = "No" in the spreadsheet. 

4. We are not certain what "known denominator-cases" means in the metadata spreadsheet. Katrina's guess: whether a state reports the total case count, which helps when a state reports cases as percentages rather than raw numbers. If so, how can AR report the number of cases but have a "No" for "known denominator-cases?"

5. Based on my [Katrina's] #crdt-web lurking, three states have changed how they report from race & ethnicity combined to separate or vice versa (GA, UT, WY). If a state changes how they report on a certain date, can we assume that cumulative numbers after that date use the new reporting scheme and cumulative numbers before that use the old scheme?

6. The columns "race & ethnicity combined" and "race & ethnicity separately" appear to have the opposite meanings that one would expect. In the doc Structured Metadata for Covid Tracking Project, we define "race & ethnicity combined" to mean that race numbers include both Hispanic and Non Hispanic and "race & ethnicity separately" to include only Non Hispanic numbers. However, the data on their site seems to indicate that "race & ethnicity combined" corresponds to Non Hispanic only while "race & ethnicity separately" corresponds to both Hispanic and Non Hispanic.

**Comment by katattack** [comment]
Another mismatch to add to #1:

FL: Website, card, dashboard, and data = combined. Metadata = separate.

**Comment by jenniebrown** [comment]
Finished this verification with results in this doc: https://docs.google.com/document/d/1lJSc050AetmFCw4JHq0pX8owRtdkrX5Zz8WHMCLK6ak/edit?resourcekey=0-5BxFke_S_4rAqDMc_WYeTw#heading=h.vsf3jfqzfqfu

Both the staging and prod pipelines have been updated with the fixed metadata.
