### ISSUE TITLE
Warm Welcome

### ISSUE THREAD

**Issue by efregoso** [SatcherInstitute/health-equity-tracker#350]
Create a "warm welcome" user tutorial to demonstrate how to use the site and how to interpret the data

**Comment by achipham** [comment]
COPY FOR 4 WW:

**Start Your Search** 
Complete the sentence by selecting a location. You can also select a different variable, like ‘Diabetes’ or ‘Poverty’


**Compare Locations and Variables**
Click the arrows to scroll left or right for more ways to search, such as ‘Compare rates of COVID-19 between Georgia and Alabama’ or ‘Explore relationships between Diabetes and Health Insurance in the United States’


**Limits in the Data**
The Tracker ingests and standardizes many data sets, but unfortunately there is missing, incomplete, or misclassified data in our sources. 

*We acknowledge that deep inequities exist in the very structure we use to collect and share data. We are committed to helping to fix this.


**Explore Further to See Trends**
Where available, the tracker offers breakdowns by race and ethnicity, sex, and age. This is currently limited to the national and state level, with county-level data coming soon.

**Comment by kkatzen** [comment]
still need to update this to add cookies
