### ISSUE TITLE
Create simple e2e test for one of the cloud run services

### ISSUE THREAD

**Issue by mayaspivak** [SatcherInstitute/health-equity-tracker#36]
E.g. for the data serving service, it could be a placeholder test that invokes the service and ensure it returns “Hello World”

**Comment by jenniebrown** [comment]
@mayaspivak were you thinking that these tests should use the Test deployment or that they would stand up their own instances in the same process? I can see a case for either, just wondering which you were thinking of when you added this.

**Comment by mayaspivak** [comment]
I was thinking they would use the test deployment so they would run after the terraform steps update the test deployment.
