### ISSUE TITLE
Data Dashboard: Move all “Coming Soon” options to bottom of dropdown / making them not clickable

### ISSUE THREAD

**Issue by efregoso** [SatcherInstitute/health-equity-tracker#369]
All the current "Coming Soon" options in the dropdowns are clickable and in alphabetical order with the rest of the list.  
We want to move them so that they are at the bottom of the list and greyed out/unclickable.

Another consideration for these is to remove them altogether.  This will be considered again after implementation.

**Comment by efregoso** [comment]
Completion time estimate: < 1 week

**Comment by kkatzen** [comment]
Team decided to remove these all-together. Closing issue
