### ISSUE TITLE
Data Dashboard: Separating the overlaid bars in the “Percent Share” bar chart and placing them side-by-side with equal width

### ISSUE THREAD

**Issue by efregoso** [SatcherInstitute/health-equity-tracker#375]
Currently, the bars in the "Percent share" bar chart card are overlaid and of different widths. 
For ease of comparison and in response to user testing feedback, we want to place these bars side by side instead, and make them of equal width.

**Comment by aaronsn** [comment]
This seems like low priority, right?

**Comment by efregoso** [comment]
Agreed -- In general, anything not marked with the "high priority" label is
considered mid-to-low priority.
