### ISSUE TITLE
Data Dashboard: Only show dropdown options on type-in location field when user has typed 1+ characters

### ISSUE THREAD

**Issue by efregoso** [SatcherInstitute/health-equity-tracker#377]
Currently, the type-in field for selecting a location presents a dropdown of every location available on the first user click.
We want to amend this so that this option dropdown only presents when a user has typed in at least 1 character as they are searching for their location. 

Another consideration for this could be subcategorizing the options in the location dropdown and alphabetizing them; this can be considered further after implementation.

**Comment by aaronsn** [comment]
Why do we not want to show the dropdown until they start typing?

**Comment by efregoso** [comment]
Chi, Larry, and I thought that showing the dropdown list immediately could
be a bit overwhelming, and that it seemed to indicate to users that they
could scroll through the available options to find their location when
really the list itself is pretty massive.

At least until the list can be furrher categorized into States/Counties, we
figured the trigger for the list appearing could be the effort to search
it.  Thoughts?

**Comment by aaronsn** [comment]
I don't have a strong opinion. That explanation makes sense, though I agree that a better experience is a list that shows counties nested under states rather than one massive alphabetical list.

This also seems low priority relative to other UX issues?
