### ISSUE TITLE
Data Dashboard: Separating “vs Population / per 100,000 people” suboptions in Percent share card into their own cards

### ISSUE THREAD

**Issue by efregoso** [SatcherInstitute/health-equity-tracker#378]
Currently, the "Percent share" card contains two suboptions, "vs Population" and "per 100,000 people", that manipulate the bar chart component below.
We want to pull these suboptions into their own cards, with their own bar charts, and place them next to each other at the top of the page, directly below the "Location Profile" card and the future minimap card.

**Comment by kkatzen** [comment]
For this, I might just branch the existing card into two new cards in case people ever want to use the current card again (even if just as a coding example)
