### ISSUE TITLE
Add small multiples to MapCard

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#389]

**Comment by kkatzen** [comment]
Bare minimum functionality is submitted, but there's still some fit&finish to be done here with UX and copy regarding the math of the scales

**Comment by kkatzen** [comment]
![Screen Shot 2021-03-15 at 10 21 36 AM](https://user-images.githubusercontent.com/6402808/111197598-e4247c00-857b-11eb-8689-45f38c3efd86.png)

Update filter to support age and sex breakdowns

**Comment by efregoso** [comment]
Completion time estimate: < 1 week

**Comment by achipham** [comment]
Change color scheme to #yellowgreen 
https://screenshot.googleplex.com/7oiH7eac5EsdtSh

**Comment by achipham** [comment]
Add 16px spacing between Filter By: and Category
https://screenshot.googleplex.com/AHY9uirgg2oLm4Q

**Comment by achipham** [comment]
Change info bubble: https://screenshot.googleplex.com/86BJmLuDW7sNEba

Text:
Note that the legend changes between different categories. To see all categories at once, click 'Show full breakdowns' link

Background color: #F8F9FA
Outline + info icon: #0B5240

<img width="603" alt="Screen Shot 2021-03-18 at 1 11 49 PM" src="https://user-images.githubusercontent.com/31259975/111683757-85653980-87eb-11eb-99d6-7e6d0d0683b6.png">

**Comment by achipham** [comment]
Modal popup changes: https://screenshot.googleplex.com/7PHHDYshbczQYEL
