### ISSUE TITLE
Data Dashboard: Merge Hispanic race categories with non-Hispanic counterparts

### ISSUE THREAD

**Issue by efregoso** [SatcherInstitute/health-equity-tracker#391]
Currently, we make the distinction between Hispanic/non-Hispanic ethnicity with two different racial categories, "x" & "x (Non-Hispanic)".
We want to combine these two categories.

Backend is working on creating a binary "Hispanic?" category, but in the meantime let's combine these two in visualizations on the frontend.

**Comment by aaronsn** [comment]
I don't think it's worth making a workaround for this, given limited time till launch. Once schema changes happen, the frontend will need to switch from using race_and_ethnicity to using just race

**Comment by aaronsn** [comment]
We also need to make sure that if we're merging data across states that report differently, that we have a footnote indicating this

**Comment by efregoso** [comment]
Completion time estimate: < 2 weeks

**Comment by kkatzen** [comment]
Is this issue still valid? I agree with Aaron that I don't think we should make a workaround in the frontend if the backend is providing the wrong data format given the tight launch time

**Comment by kkatzen** [comment]
Also wanted to make note of these two issues dealing with how we handle hispanic vs non-hispanic data in frontend: 
https://github.com/SatcherInstitute/health-equity-tracker/issues/475
https://github.com/SatcherInstitute/health-equity-tracker/issues/307

**Comment by vanshkumar** [comment]
The latest on this after the discussion with Ebony is to not alter the race/ethnicity labels that we show (and so not have the footnote explaining that all categories include/exclude hispanic), and instead just add a static footnote at the bottom explaining what hispanic/latino means per dataset. What the footnote is going to say & how it's going to vary exactly per dataset is not totally clear right now

**Comment by adams314** [comment]
I'm going to close this issue. We will open a separate issue to define whatever footnote we add for hispanic/latino. But we aren't consolidating any groups or altering labels per Vansh's most recent comment
