### ISSUE TITLE
Error links go no where

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#431]
![Screen Shot 2021-03-11 at 3 44 29 PM](https://user-images.githubusercontent.com/6402808/110870135-b809b200-8280-11eb-9f5d-824ef8cfbe68.png)

Error alerts made for UX testing go nowhere

**Comment by kkatzen** [comment]
Aaron has suggested these would look better left aligned

**Comment by efregoso** [comment]
Completion time estimate: < 1 day, pending content approval for "Roadmap" and "Contact Us" pages

**Comment by kkatzen** [comment]
Disable the madlibs that don't have data (and show these messages) and then we can delete these messages

**Comment by kkatzen** [comment]
Larry says we don't want any coming soon options in the dropdown.
