### ISSUE TITLE
Bar chart bug

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#437]
![Screen Shot 2021-03-15 at 10 17 22 AM](https://user-images.githubusercontent.com/6402808/111197655-f43c5b80-857b-11eb-8887-1bd04c2be42e.png)
![Screen Shot 2021-03-15 at 10 16 42 AM](https://user-images.githubusercontent.com/6402808/111197679-fd2d2d00-857b-11eb-8256-0ec8b6bafcae.png)

**Comment by efregoso** [comment]
Completion time estimate: < 1 week

**Comment by kkatzen** [comment]
Did you figure out what was wrong with it, Elizabeth? I didn't start looking into it yet

**Comment by kkatzen** [comment]
cannot replicate
