### ISSUE TITLE
Population Card: Calculate median age

### ISSUE THREAD

**Issue by efregoso** [SatcherInstitute/health-equity-tracker#464]

**Comment by vanshkumar** [comment]
IMO this is not needed for launch and we can throw it on the backlog

**Comment by benhammondmusic** [comment]
@jgonzalezmsm Is this still a feature we want to include, or should we close this issue? Would it be helpful to display median age on the population card dropdown ? 

<img width="1698" alt="expanded pop card" src="https://user-images.githubusercontent.com/41567007/132627888-080a27c9-fa26-4ab4-acc9-457ddd34d265.png">

**Comment by jgonzalezmsm** [comment]
Let's ask the team. I don't see a huge value in it and at the risk of more screen clutter I'm not sure if it's something we want to do unless we come up with some low cost way to do it?
