### ISSUE TITLE
Small multiples layout looks a bit odd

### ISSUE THREAD

**Issue by vanshkumar** [SatcherInstitute/health-equity-tracker#485]
The alignment is a bit odd for the small multiples maps - in the screenshot, the last two maps being off-center vs the other maps looks a bit weird

![image](https://user-images.githubusercontent.com/3394642/112679631-a18b5b00-8e29-11eb-8e51-a3f05b70584a.png)

**Comment by benhammondmusic** [comment]
This looks like a "space evenly" vs "space around" or "space between" situation with css flex. I'll try some other options and see what looks better
