### ISSUE TITLE
Add title to Small Multiples overlay

### ISSUE THREAD

**Issue by adams314** [SatcherInstitute/health-equity-tracker#497]
When a user views the small multiples breakdown, they lose the context of what metrics are being compared across groups.

The title structure should be:

[Metric] across all [Breakdown] groups, e.g.: 

*COVID-19 deaths per 100,000 people in United States* across all *Race and Ethnicity* groups

**Comment by kkatzen** [comment]
![Screen Shot 2021-04-01 at 10 56 29 AM](https://user-images.githubusercontent.com/6402808/113335132-6087c080-92d9-11eb-983e-29f1ef5b5c21.png)
