### ISSUE TITLE
Investigate why BRFSS datasets aren't displaying properly

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#515]
COPD and diabetes, the table isn't populating "share of diabetes cases"

let's investigate if 
1) we're actually pulling this data from the backend
2) why share of diabetes cases isn't working

**Comment by vanshkumar** [comment]
From our discussion, what's needed to get this working for BRFSS is:
- Join with ACS to get pop
- Use per100k * 100k or yes / (yes + no) and multiply by pop numbers and save as a col
- Use that col to do % share calculations

Estimate is 2-3 days of work

**Comment by aaronsn** [comment]
Pasting my comment from slack for ease of reference:

This requires joining with ACS at the state level before doing the pivoting to the national level that happens [here](https://github.com/SatcherInstitute/health-equity-tracker/blob/a5b3bcea954147e3460b21d11dc28517f0f1174a/frontend/src/data/variables/BrfssProvider.ts#L32). The problem with doing it after the pivot is it introduces data skew if different states have different survey rates. (eg one state has a larger population but sampled a smaller # of people, so its results are underrepresented in the totals). You'll need to 1) Get ACS data at the state level, 2) for each state estimate total case count using (cases / (cases + no_cases)) * population , 3) pivot to national level and sum estimated case counts to get estimated case counts at the national level, 4) finally use national-level case count estimates to calculate national level %
