### ISSUE TITLE
Calculate CdcProvider reporting_populations

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#518]
Address this TODO: https://github.com/SatcherInstitute/health-equity-tracker/blob/2c4f8136e10a0ee96a6a4aba67a1359686004ef9/frontend/src/data/variables/CdcCovidProvider.ts#L114

**Comment by kkatzen** [comment]
reporting populations should sum ACS population demographics exclusively based on the geographies that reported data for the metric

**Comment by vanshkumar** [comment]
Closing this per latest discussion.. we can't do this as we can't tell if a county isn't reporting cases or just has zero cases
