### ISSUE TITLE
Unknown Map Legend

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#520]
Some of these legends look weird... should we consider switching the legend type?

![Screen Shot 2021-04-01 at 5 21 35 PM](https://user-images.githubusercontent.com/6402808/113366685-c8a4c980-930e-11eb-901c-1b68c24778ac.png)

**Comment by adams314** [comment]
Duplicate of #257

**Comment by kkatzen** [comment]
Are we sure it's okay that the darkest color isn't on the legend? May be a vega bug... I'll look into seperate from how we handle the legend display
