### ISSUE TITLE
Audit data sources content

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#542]
Eng made up the text on the cards on this page: https://dev.healthequitytracker.org/datacatalog
Notice how the link below the title is the exact same text...

Product should create final copy

**Comment by kkatzen** [comment]
Notice that the demographic granularity filter is based on the literal text... I'm not sure how useful this / it's maybe misleading since the granularity isn't all of those together but rather all of those separately... we may want to just remove

**Comment by kkatzen** [comment]
From Larry: they are working on updating that content, we can go ahead and remove the expand (show more/less) toggle

**Comment by kkatzen** [comment]
We'll remove all filters for now

**Comment by vanshkumar** [comment]
I looked through the page, made a couple edits to the text, and downloaded each of the datasets and they all seemed usable to me

**Comment by vanshkumar** [comment]
Chatted with Larry, we're good to go here except for the CDC restricted disclaimer (which is being tracked in a different issue)
