### ISSUE TITLE
Think about if we want to change dataset refresh rate of 24 hrs

### ISSUE THREAD

**Issue by vanshkumar** [SatcherInstitute/health-equity-tracker#550]
This was put in to avoid out-of-date FEs, perhaps we should tweak the number

**Comment by aaronsn** [comment]
Code pointer: https://github.com/SatcherInstitute/health-equity-tracker/blob/a5b3bcea954147e3460b21d11dc28517f0f1174a/frontend/src/data/loading/DataManager.ts#L57-L61
