### ISSUE TITLE
Enable gzip compression for better initial load performance on frontend

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/health-equity-tracker#554]
We'll probably want to use an Express.js middleware for compression. There are a few headers to make sure are present on the frontend per https://github.com/SatcherInstitute/health-equity-tracker/issues/253#issuecomment-815984834, but I'm guessing the middleware will take care of that automatically.

**Comment by benhammondmusic** [comment]
There could be large performance gains here since we are shipping giant uncompressed json files to the client. Lighthouse recommends exactly this; also could serve both brotli and gzip as options
