### ISSUE TITLE
Disparities chart for Diabetes and COPD at National Level is broken

### ISSUE THREAD

**Issue by adams314** [SatcherInstitute/health-equity-tracker#588]
<img width="705" alt="Screen Shot 2021-04-13 at 1 47 44 PM" src="https://user-images.githubusercontent.com/80131692/114598263-b5272600-9c5f-11eb-9703-f1d5a04252aa.png">

**Comment by adams314** [comment]
Also reportedly broken for COPD

**Comment by joshzarrabi** [comment]
Hi @adams314! Thank you for bringing this to our attention. We already have a fix for this ready to go.

Closed in favor of https://github.com/SatcherInstitute/health-equity-tracker/issues/515
