### ISSUE TITLE
Use proper `_RACE` race categorization with BRFSS data instead of `Imputed Race`

### ISSUE THREAD

**Issue by joshzarrabi** [SatcherInstitute/health-equity-tracker#591]
### Background

The BRFSS survey has a few different ways of categorizing race, all defined [here](https://www.cdc.gov/brfss/annual_data/2019/pdf/codebook19_llcp-v2-508.HTML).

Currently we use the `Imputed Race` category, which is defined as: `Imputed race/ethnicity value  (This value is the reported race/ethnicity or an imputed race/ethnicity, if the respondent refused to give a race/ethnicity. The value of the imputed race/ethnicity will be the most common race/ethnicity response for that region of the state)`.

It allows for the following race categorizations:

* White, Non-Hispanic
* Black, Non-Hispanic
* Asian, Non-Hispanic
* American Indian/Alaskan Native, Non-Hispanic
* Hispanic
* Other race, Non-Hispanic

### Problems

There are a few issues with using the `Imputed Race` category

* It is unclear how multi-race people are counted.
* There is no category for "Pacific Islander and Native Hawaiian", which the other data sets we use do have.
* It lacks a more detailed description in the [computed values](https://www.cdc.gov/brfss/annual_data/2019/pdf/2019-calculated-variables-version4-508.pdf) document, which describes in detail what other race categories mean.
* The fact that values are imputed with the most common race/ethnicity for that region of the state is a questionable way to guess and could lead to over or underrepresentation of demographics.  

### Proposed Solution

We should switch to using the `_RACE` column in the BRFSS data because it ....

* Properly categorizes multi-racial people.
* Has a category for "Native Hawaiian and Pacific Islander".
* Does not attempt go guess or "impute" anyone's racial category.
* Is properly defined, as shown below

![Screen Shot 2021-04-12 at 4 18 12 PM](https://user-images.githubusercontent.com/3689026/114725823-d4c75880-9d0a-11eb-91b2-3026fcc6952b.png)

**Comment by aaronsn** [comment]
> an imputed race/ethnicity, if the respondent refused to give a race/ethnicity. The value of the imputed race/ethnicity will be the most common race/ethnicity response for that region of the state

Also doesn't this mean that it's just making a potentially incorrect assumption about race, and inflating the numbers for some groups?

**Comment by joshzarrabi** [comment]
> > an imputed race/ethnicity, if the respondent refused to give a race/ethnicity. The value of the imputed race/ethnicity will be the most common race/ethnicity response for that region of the state
> 
> Also doesn't this mean that it's just making a potentially incorrect assumption about race, and inflating the numbers for some groups?

Yeah I will add that in
