### ISSUE TITLE
Decide what to do about weird ACS health insurance / poverty age buckets

### ISSUE THREAD

**Issue by vanshkumar** [SatcherInstitute/health-equity-tracker#592]
The age buckets for ACS health insurance and poverty are odd, e.g. poverty contains buckets such as 0-5, 5, 6-11, 12-14, 15, 17 - there seems to be overlap between 0-5 and 5, there is no 16 bucket, and having individual ages is odd. Health insurance is better, but has 0-6 and 6-18 buckets which are somewhat nonstandard.

We should at minimum sort these numerically rather than alphabetically, so they show up in order in the UI, and also decide if we want to show these odd buckets, aggregate them somehow, etc.

**Comment by aaronsn** [comment]
I think the 0-5/5 overlap is a bug in the standardization. The actual ACS bucket says ["under 5"](https://api.census.gov/data/2019/acs/acs5/groups/B17001.html) but the code looks like it's setting the upper end of the bucket to 5:

https://github.com/SatcherInstitute/health-equity-tracker/blob/2fa6e740cbd16a37e9b6d9352f6c579d0effd806/python/ingestion/acs_utils.py#L16

**Comment by vanshkumar** [comment]
We chatted about this problem in the sync with MSM this morning, I think there are actually 4 separate issues here that we should address:

1. Fixing the standardization bug in acs_utils that Aaron mentioned in the previous comment
2. Sorting the age buckets numerically rather than alphabetically
3. Converting the weird age buckets in ACS poverty to more 'normal' age buckets. Specifically, the MSM folks suggested the following buckets: 0-5, 6-11, 12-17. This will require aggregation logic, which it likely makes the most sense to put into the python processing code (as opposed to SQL).
4. Spending at least a little bit of time trying to understand why the age 16 doesn't show up in any of the buckets.. this seems kind of fishy to me

Let me know if you have any questions about any of this or feel that we need to split up the work, Seth!

**Comment by vanshkumar** [comment]
I also just noticed another oddity with the ACS health insurance ages, it looks like both 65+ and 65-74 are in the data.. will check with MSM folks on if we want to show both or suppress one of them.

**Comment by Sethvg** [comment]
65+ and 65-74 is a bug.  This is addressed in the refactor as it parses the labels rather than having a manual mapping (Chance for error).  The actual buckets are 65-74, 74+

**Comment by vanshkumar** [comment]
Last item left here is to sort the ages numerically rather than alphabetically
