### ISSUE TITLE
Diabetes/COPD Cases by Race and Ethnicity cards have both race and race (Non-Hispanic) categories

### ISSUE THREAD

**Issue by vanshkumar** [SatcherInstitute/health-equity-tracker#593]
We should only show the races for which we actually have data. Based on looking through the code, the best guess for why this is happening is that the populationComparisonMetric in the MetricConfig is coming from ACS population provider, whereas the raw metric (e.g. diabetes_count) comes from the BRFSS provider. Simplest fix is to join with ACS pop for all cases in the BRFSS provider (right now we only do it for national geo) & use the resulting population metric as the populationComparisonMetric, so we are sure to only include races for which we have data.

**Comment by vanshkumar** [comment]
This issue is popping up for the ACS health insurance data, and presumably will for poverty as well (see [this comment](https://github.com/SatcherInstitute/health-equity-tracker/pull/580#pullrequestreview-636121309)). We likely will want to apply whatever fix we find for the BRFSS data to those as well

**Comment by joshzarrabi** [comment]
Done in https://github.com/SatcherInstitute/health-equity-tracker/pull/613
