### ISSUE TITLE
Extract unknown map into its own card

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#602]
Take the warning and the unknowns map card that's currently in the disparity bar chart and pull it into its own card

**Comment by kkatzen** [comment]
Have a PR out, still need sign off on the copy/ux/placement of the card. See deploy preview https://deploy-preview-607--health-equity-tracker.netlify.app/exploredata

**Comment by kkatzen** [comment]
From Larry:
1. title = “Share of total Covid-19 cases in United States with Unknown Values for Race and Ethnicity”
2. Add warnings to BOTH map cards with UNKNOWN or KNOWN in all caps: "/!\ 42.9% of cases in reported had an unknown value for race and ethnicity. This chart displays data for cases where race and ethnicity was UNKNOWN"

**Comment by adams314** [comment]
Add warning to Share of total cases with unknown values:
/!\ 42.9% of cases in reported had an unknown value for race and ethnicity. This chart displays data for cases where race and ethnicity was UNKNOWN

Update warning in Disparity chart
/!\ 42.9% of cases in reported had an unknown value for race and ethnicity. This chart only displays data for cases where race and ethnicity was KNOWN

**Comment by adams314** [comment]
Updating per Chi's suggestion:

Add warning to Share of total cases with unknown values:
/!\ 42.9% of cases in reported had an unknown value for race and ethnicity. The chart below displays data for cases where race and ethnicity was UNKNOWN

Update warning in Disparity chart
/!\ 42.9% of cases in reported had an unknown value for race and ethnicity. The chart below only displays data for cases where race and ethnicity was KNOWN

**Comment by adams314** [comment]
Correcting grammar

Add warning to Share of total cases with unknown values:
/!\ 42.9% of cases reported an unknown value for race and ethnicity. The chart below displays the cases where race and ethnicity was UNKNOWN

Update warning in Disparity chart
/!\ 42.9% of cases reported an unknown value for race and ethnicity. The chart below only displays data for cases where race and ethnicity was KNOWN

**Comment by adams314** [comment]
Just bumping this to note that we still need to add the warning to the card that maps the unknown values:

/!\ 42.9% of cases reported an unknown value for race and ethnicity. The chart below displays the cases where race and ethnicity was unknown
