### ISSUE TITLE
Update title and styles in unknown demographics card

### ISSUE THREAD

**Issue by adams314** [SatcherInstitute/health-equity-tracker#641]
1. Change Title for unknowns card to:

Unknown (DEMOGRAPHIC} for {Selected Datatype} 

e.g.: Unknown Race and Ethnicity for Share of total COVID-10 cases

2. Change map colors to warm grayscale

![image](https://user-images.githubusercontent.com/80131692/115759120-e691a700-a36d-11eb-9790-490d7b415825.png)

**Comment by kkatzen** [comment]
Closed in https://github.com/SatcherInstitute/health-equity-tracker/pull/644
