### ISSUE TITLE
Update Alert on the Small Multiples Overlay

### ISSUE THREAD

**Issue by adams314** [SatcherInstitute/health-equity-tracker#655]
Remove the text below "Compare with Caution" and replace with:

xx.x% of cases reported unknown {demographic}. The charts below display data for cases where {demographic} was known. [View map of where unknown values are being reported]()

Clicking on the link should update the contents of the overlay to include only the unknowns map for the selected demographic.

**Comment by kkatzen** [comment]
We're talking about this dialog right?

![Screen Shot 2021-04-23 at 7 30 39 PM](https://user-images.githubusercontent.com/6402808/115944407-6e5cdb80-a46a-11eb-9a9a-f858b45ac337.png)

by "only unknowns map for the selected demographic" do you mean the same chart as the Unknowns top-level card? so the multiple maps are replaced by just 1 map that's already on the main screen? Is it a link or a toggle? I'm not sure I understand...

**Comment by adams314** [comment]
Yes, I mean a link that pulls up the unknowns map by itself in this dialog/overlay. A toggle sounds better though so you can switch back and forth without closing the window. 

If we could switch back to the main dash and focus on the unknowns graph that might work in a single column display but in our double column display I'm worried the user gets lost and doesn't realize we're directing them to the unknowns chart.

**Comment by adams314** [comment]
Per discussion in the disclaimers doc, let's just remove the caution in the overlay for now and leave the unknown warnings to the main page
