### ISSUE TITLE
Look into doing a crosshatch overlay for TX, LA, WY, NH in covid unknowns map

### ISSUE THREAD

**Issue by vanshkumar** [SatcherInstitute/health-equity-tracker#683]
Unknowns map looks weird for these states for which we are suppressing all data, as they show up as light gray. We should see if it's possible to do a crosshatch overlay / generally how hard it is to show different styles on the map for these specific states in Vega

![image](https://user-images.githubusercontent.com/3394642/116135014-903ea400-a69e-11eb-893f-90baea3cfbad.png)

**Comment by kkatzen** [comment]
issue #498 has relevant links

**Comment by adams314** [comment]
Could we try rendering the unknowns map using the "blues" vega color scheme? It aligns with our brand/style guide (although the hex codes aren't exactly the same)

https://docs.google.com/presentation/d/1w9_W9wpOIgu32HxKvScwSg2KAfqDrqW-HCnhS1hpqD0/edit#slide=id.gc476b52e1d_0_126

**Comment by kkatzen** [comment]
![Screen Shot 2021-04-27 at 10 48 08 AM](https://user-images.githubusercontent.com/6402808/116288199-1eba3080-a746-11eb-8e40-ab1a4f73122f.png)

If you go to "Open in Vega Editor" on the charts you can update the colors and check out for yourself.  You just need to update the counties-10m.json URL with:
https://raw.githubusercontent.com/SatcherInstitute/health-equity-tracker/master/frontend/public/counties-10m.json

Search "warmgreys" in the vega config and update to see different versions

**Comment by adams314** [comment]
Thanks...I tried opening in vega editor but when I edited and ran, it only gave me the legend. 

What do you think Chi?

<img width="1135" alt="Screen Shot 2021-04-27 at 2 10 04 PM" src="https://user-images.githubusercontent.com/80131692/116291241-5afb8a00-a762-11eb-87b6-f8132d04973a.png">

**Comment by kkatzen** [comment]
Did you update the counties-10m.json value with "https://raw.githubusercontent.com/SatcherInstitute/health-equity-tracker/master/frontend/public/counties-10m.json"?

**Comment by kkatzen** [comment]
resolving this by changing warm grey into "greenblue"
