### ISSUE TITLE
Frontend linter

### ISSUE THREAD

**Issue by efregoso** [SatcherInstitute/health-equity-tracker#711]
At Krista's suggestion: Finding a frontend linter.

**Comment by kkatzen** [comment]
What exactly does this refer to? I've suggested we each use a linter in our own IDEs. Aaron and I both did this so our changes are automatically linted when we commit. Is this bug to add one to the repo?

**Comment by aaronsn** [comment]
I think this is a dupe of https://github.com/SatcherInstitute/health-equity-tracker/issues/245. Ideally we set up the linter on the project so that the PR checks will enforce it even if devs don't have it set up in their own IDE
