### ISSUE TITLE
Race standardization for ACS health ins seems to be broken

### ISSUE THREAD

**Issue by vanshkumar** [SatcherInstitute/health-equity-tracker#712]
See screenshot, somehow this seems to have gotten broken and is showing the race labels directly:

![image](https://user-images.githubusercontent.com/3394642/116623871-c6c52a80-a8fb-11eb-946e-2ce3d3b5168e.png)

**Comment by aaronsn** [comment]
Looks like in https://github.com/SatcherInstitute/health-equity-tracker/pull/681 add_race_columns_from_category_id got dropped and race_category_id switched back to race, so now the frontend is reading the "race" col and getting the category ids.

**Comment by vanshkumar** [comment]
Fixed
