### ISSUE TITLE
Update unknowns map card when no county level data

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#719]
Current version is kind of confusing:
<img width="1234" alt="Screen Shot 2021-04-29 at 10 35 26 PM" src="https://user-images.githubusercontent.com/6402808/116653060-47efe200-a93b-11eb-9387-4315e88ee27c.png">

Do we want to update this somehow?
Maybe update the second alert to indicate it's the county level breakdown that is missing and add a grey county level map like the MapCard? Will it be too weird to have two alerts?

**Comment by vanshkumar** [comment]
I think this issue is obsolete now that diabetes does not have any concept of unknown race/ethnicity since we switched to the united health foundation data recently

**Comment by kkatzen** [comment]
I think we should still consider showing an empty map on unknowns card to match the other map card in cases like this: 
![Screen Shot 2021-05-03 at 5 56 17 PM](https://user-images.githubusercontent.com/6402808/116950086-e41a3180-ac38-11eb-8ea1-4f1bfc7c7cd9.png)

**Comment by vanshkumar** [comment]
Ah sorry I think I misunderstood what this issue is about a little.. agree that we should update the warning to indicate that it's county-level data that is missing & should still show the grey map

**Comment by adams314** [comment]
I think it's ok to show an empty map.

The message should be updated to state:

"We do not currently have {CONDITION} data broken down by {DEMOGRAPHIC} at the county level"
