### ISSUE TITLE
ACS population ingestion & standardization

### ISSUE THREAD

**Issue by katattack** [SatcherInstitute/health-equity-tracker#72]
https://www.census.gov/data/developers/data-sets.html
We should use the 5-year ACS (2014-2018).

We'll need to decide what age buckets we want to use to standardize with other datasets.

**Comment by aaronsn** [comment]
This reminds me - do we know what degree of intersection between different breakdowns we want for population characteristics? Eg, do we want to be able to query for "population of black women between 30 and 40 years old", which would require breaking down by age/gender/race at the same time?

I guess the more breakdowns we can do the more granular of questions we can answer but also raises questions about the accuracy of the data, how to handle missing data or small population slices, and whether other datasets have the same degree of breakdowns.

**Comment by ldbnr4** [comment]
The only variable intersections I found in the source were age and gender. For example we'll have population data on women over 18 but without a race breakdown. 

We could try and derive a race breakdown by making an assumption that gender ratios are uniform across all races and multiply race population by the age/gender percentage but we should call out this assumption.

Details on the variable breakdowns: https://api.census.gov/data/2018/acs/acs5/profile/variables.html

**Comment by ldbnr4** [comment]
The [detailed table](https://api.census.gov/data/2018/acs/acs5/variables.html) gives us the intersections of age/gender/race at the state level.

**Comment by aaronsn** [comment]
I'm currently working on this

**Comment by aaronsn** [comment]
Closing this out since the main work is done. Forked off several issues for followups:
- https://github.com/SatcherInstitute/health-equity-tracker/issues/339
- https://github.com/SatcherInstitute/health-equity-tracker/issues/340
- https://github.com/SatcherInstitute/health-equity-tracker/issues/341
- https://github.com/SatcherInstitute/health-equity-tracker/issues/342
