### ISSUE TITLE
Update disparity bar chart ticks

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#720]
Current amount is a little aggressive
<img width="554" alt="Screen Shot 2021-04-29 at 10 45 04 PM" src="https://user-images.githubusercontent.com/6402808/116653743-a49fcc80-a93c-11eb-94ab-080cc0d9873c.png">

**Comment by benhammondmusic** [comment]
tickMinStep	Number	The minimum desired step between axis ticks, in terms of scale domain values. For example, a value of 1 indicates that ticks should not be less than 1 unit apart. If tickMinStep is specified, the tickCount value will be adjusted, if necessary, to enforce the minimum step value. 

https://vega.github.io/vega/docs/axes/
