### ISSUE TITLE
Bar chart label issues

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#721]
<img width="576" alt="Screen Shot 2021-04-29 at 10 48 47 PM" src="https://user-images.githubusercontent.com/6402808/116653975-16781600-a93d-11eb-97ed-d2fb810a07d7.png">

**Comment by aaronsn** [comment]
Just a guess, but this often happens when there are multiple rows with the same y-axis value. Vega will just drop them all on top of each other

**Comment by kkatzen** [comment]
![Screen Shot 2021-05-06 at 1 49 38 PM](https://user-images.githubusercontent.com/6402808/117363810-f206c700-ae71-11eb-8d76-b1ff47dc289e.png)
Not reproducible - maybe the dataset got fixed
