### ISSUE TITLE
Look into NYC counties COVID data

### ISSUE THREAD

**Issue by joshzarrabi** [SatcherInstitute/health-equity-tracker#727]
### Problem

Right now, if you want to investigate rates of COVID in New York City, and type `New York City` into the Mad Lib, the tracker says the data is missing. 
<img width="1832" alt="Screen Shot 2021-05-01 at 12 53 32 PM" src="https://user-images.githubusercontent.com/3689026/116789459-e3d53700-aa7c-11eb-86ed-e8dc4d8afeb8.png">

However, if you click into the map from New York State into New York County (which is Manhattan), you do get a properly filled out county, however it is called `undefined`.  This is the same for all five New York City Counties

<img width="1324" alt="Screen Shot 2021-05-01 at 1 00 54 PM" src="https://user-images.githubusercontent.com/3689026/116789544-5f36e880-aa7d-11eb-9b13-420f3f9b2207.png">

### What I expect to happen

You should be able to search for NYC counties like any other.

**Comment by vanshkumar** [comment]
Confirmed I can reproduce this. Here's a sample of the CDC restricted data from bigquery for New York County:

![image](https://user-images.githubusercontent.com/3394642/116957701-60b70b00-ac4d-11eb-8f4e-4cd608f0b2e6.png)

I verified that data is also present for another borough of NYC (King's County), so not sure why this is happening. Continuing to investigate
