### ISSUE TITLE
Update title of "Disparities" charts

### ISSUE THREAD

**Issue by adams314** [SatcherInstitute/health-equity-tracker#736]
The charts doesn't necessarily display disparities depending on the underlying data, although it often does.

Chart title for affected vs. total population should be:

"Share of total {CONDITION} by {DEMOGRAPHIC} vs. {DEMOGRAPHIC'S} share of population in {LOCALE}"

Chart title for rate/100K:

"{CONDITION} per 100,000 people by {DEMOGRAPHIC} in {MINNESOTA}"

**Comment by efregoso** [comment]
@kkatzen Would you be able to do this on Thu?
