### ISSUE TITLE
Add another tab to What is Health Equity for "Resources" 

### ISSUE THREAD

**Issue by adams314** [SatcherInstitute/health-equity-tracker#737]
SHLI collected a bunch of health equity resources from the task force they would like to include on the site. We should include it in the "What is Health Equity" page as a new tab after FAQ.

Tab title: "Health Equity Resources"
Tab content: tbd list of links and description of each link.

**Comment by efregoso** [comment]
I can draft this, but I think it would be best to wait until the resources list is complete before pushing to the dev site?

**Comment by adams314** [comment]
SGTM!

**Comment by adams314** [comment]
FYI, still waiting final list of URLs for this. will set a deadline for later today.
