### ISSUE TITLE
Map doesn't have all geographies supported by MadLib

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#760]
![Screen Shot 2021-05-06 at 10 27 49 AM](https://user-images.githubusercontent.com/6402808/117340483-c675e380-ae55-11eb-9306-fac9f8235591.png)

**Comment by vanshkumar** [comment]
Discussed in the sync today, we want to show some text acknowledging that we don't have this in our map, but this is relatively lower priority than other things

**Comment by vanshkumar** [comment]
Closing in favor of #815 and #816
