### ISSUE TITLE
Can anything be done about Outliers messing up legend here?

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#763]
![Screen Shot 2021-05-06 at 11 13 44 AM](https://user-images.githubusercontent.com/6402808/117346190-4a32ce80-ae5c-11eb-91bc-c68a74ae54a2.png)

**Comment by vanshkumar** [comment]
Since we're likely suppressing all territories' data, that will probably help quite a bit with some of the legend issues (eg Northern Mariana Islands has like 50-80% unknown age/gender whereas most states are < 1%)

**Comment by vanshkumar** [comment]
After suppressing territories' data in a PR & switching the scale for the unknowns map to a slightly modified symlog, I think it looks a lot better, deploy-preview: https://deploy-preview-867--health-equity-tracker.netlify.app/exploredata

Will ping the slack with this deploy-preview and get more thoughts after we confirm that the territory data needs to be suppressed, which will happen on Mon
