### ISSUE TITLE
How do we handle having absolutely no data?

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#777]
Should we remove from the madlib?
Should we have just one missing message?

![Screen Shot 2021-05-06 at 1 52 22 PM](https://user-images.githubusercontent.com/6402808/117364105-588be500-ae72-11eb-9e45-80bdad7fdf55.png)

**Comment by adams314** [comment]
Do not remove from the madlib. 

We should reduce the messages though if possible. I think that having just "Data Missing" next to Total Population is sufficient

**Comment by adams314** [comment]
Don't make any changes to the page...remove the warning in the profile card and leave the "Data Missing" string next to Total Population.
