### ISSUE TITLE
Update hover colors on maps

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/health-equity-tracker#784]
Waiting on new hex codes from chi

**Comment by achipham** [comment]
No data: Red Orange  #ED573F
Yes data: Dark Blue #255792.  OR. Light Blue #440 

(could I see both options for yes data?)

**Comment by achipham** [comment]
YES data options:
- Light blue #ADBBDE
- Dark green #0B5240
- Dark gray #3C4043

I'm good with the orange for NO data (#ED573F)!

**Comment by vanshkumar** [comment]
No prob, screenshots attached in the order you listed the colors:

![Screen Shot 2021-05-11 at 4 18 50 PM](https://user-images.githubusercontent.com/3394642/117896044-932bbe00-b274-11eb-9577-9e002ffe1295.png)
![Screen Shot 2021-05-11 at 4 19 22 PM](https://user-images.githubusercontent.com/3394642/117896094-a63e8e00-b274-11eb-8041-4640c97b3f2b.png)
![Screen Shot 2021-05-11 at 4 20 18 PM](https://user-images.githubusercontent.com/3394642/117896159-c79f7a00-b274-11eb-8479-04b7a249626a.png)
