### ISSUE TITLE
Suppress map card in the absence of US territory representation

### ISSUE THREAD

**Issue by efregoso** [SatcherInstitute/health-equity-tracker#816]
Currently, Vega does not support displaying information for US territories.

Until progress is made on #815, we want to hide the map card.

**Comment by vanshkumar** [comment]
Hey Elizabeth, is this a dupe of #760 ?

**Comment by kkatzen** [comment]
We sure make sure that when we hide the map card, the paired charts still line up in compare views

**Comment by kkatzen** [comment]
Does https://github.com/SatcherInstitute/health-equity-tracker/pull/853 deprecate this issue?

**Comment by vanshkumar** [comment]
Yes, I believe so

**Comment by vanshkumar** [comment]
Closing as #853 fixed this
