### ISSUE TITLE
Sort poverty small multiples map by age correctly

### ISSUE THREAD

**Issue by joshzarrabi** [SatcherInstitute/health-equity-tracker#817]
The poverty by age small multiples map still has ages 6-11 out of order 

![Screen Shot 2021-05-11 at 5 26 12 PM](https://user-images.githubusercontent.com/3689026/117887078-27e6e980-b27e-11eb-9109-c68e04c9b058.png)

**Comment by vanshkumar** [comment]
Should have been fixed by #825
