### ISSUE TITLE
Add dropdown to show five most and least affected locales

### ISSUE THREAD

**Issue by joshzarrabi** [SatcherInstitute/health-equity-tracker#826]
### Problem

As a user of the site, it is difficult to find the most and least affected locales for a given demographic. For example, I would like to know which county has the most COVID cases for hispanic people in California. 

### Proposed solution

* A banner underneath the map will be clickable to show the locales with the 5 highest cases per 100k and 5 lowest cases per 100k for the shown demographic. 

* Only those locales will be highlighted on the map, with the 5 highest cases being dark green and 5 lowest cases being light green. (This is optional if its too hard)

See Image 3 for reference

![image](https://user-images.githubusercontent.com/3689026/118017299-70f17900-b324-11eb-9876-72dfc3a39e0d.png)

**Comment by achipham** [comment]
Can we make the whole gray bar clickable for expand / collapse? Instead of just the down carrot.

**Comment by kkatzen** [comment]
We need to revisit the map updating - either removing it or working on reducing blinking and also fixing tooltips - "shouldn't say no data /misisng data" when we're filtering in this use case

**Comment by vanshkumar** [comment]
The main work is done here, leaving it open in backlog to discuss how we want the highlighting & tooltips to work post-launch

**Comment by kkatzen** [comment]
we could just add a boolean to not show any tooltips on non-highlighted geographies- would be pretty easy

**Comment by vanshkumar** [comment]
Yeah I think that's a good solution - do you want to send a fix, or should I?
