### ISSUE TITLE
Add information about not having a map of territories

### ISSUE THREAD

**Issue by joshzarrabi** [SatcherInstitute/health-equity-tracker#835]
### Use Case

As a user of the site
I want to know why the HET doesn't show Puerto Rico and other US territories on the map

### Potential Solution

Add information to the methodologies page about how vega (our mapping library) doesnt support US territories

related:
https://github.com/SatcherInstitute/health-equity-tracker/issues/760
https://github.com/SatcherInstitute/health-equity-tracker/issues/816

**Comment by kkatzen** [comment]
Not sure if https://github.com/SatcherInstitute/health-equity-tracker/pull/853 depcreates this or we just want to update about the national level map?

**Comment by vanshkumar** [comment]
I think it's probably worthwhile to still call out that the national level map doesn't show territories
