### ISSUE TITLE
Suppress COVID data from Puerto Rico

### ISSUE THREAD

**Issue by joshzarrabi** [SatcherInstitute/health-equity-tracker#837]
### Problem

According to Katrina's analysis, Puerto Rico's number of reported COVID cases is below our threshold compared to the NYtimes Data.

### Solution

We should:

* suppress the Puerto Rico COVID data
* add it to the list of suppressed states in the disclaimers
* change the text of the disclaimer to say "states and territories"

**Comment by vanshkumar** [comment]
Based on Katrina's latest analysis, the data for Puerto Rico is complete enough that we do not need to suppress it:

![Screen Shot 2021-05-17 at 9 40 08 AM](https://user-images.githubusercontent.com/3394642/118525296-e037e600-b6f3-11eb-96eb-3a27446af021.png)
