### ISSUE TITLE
Implement Data Server API

### ISSUE THREAD

**Issue by jenniebrown** [SatcherInstitute/health-equity-tracker#84]
The Data Server will expose two API methods for the frontend: /getMetadata and /getDataset. Implement these two in a cloud run service. See https://docs.google.com/document/d/1viK-Z8J2Y92ZaM4SqxUiylQiwkVsTfarjVeTH4LkTww/edit for details.

**Comment by mayaspivak** [comment]
I believe what is left here is to implement getDataset method.
