### ISSUE TITLE
Get rid of "with known demographics"

### ISSUE THREAD

**Issue by vanshkumar** [SatcherInstitute/health-equity-tracker#891]
![image](https://user-images.githubusercontent.com/3394642/118704592-25c7e200-b7cc-11eb-99ac-f96e46186eb6.png)

Keep this information available in the methodology page

**Comment by kkatzen** [comment]
I think we should be able to remove knownDemographics from config: 
https://github.com/SatcherInstitute/health-equity-tracker/blob/6f9f09150a3b63ed6b61956ed09511af5b3b1161/frontend/src/data/config/MetricConfig.ts#L159

I think that metric is just using the basic population data anyway

**Comment by vanshkumar** [comment]
Hmm, do you mean get rid of knownBreakdownComparisonMetric and then have the basic "_share" metrics do the known computation? Maybe the issue description is unclear, we just want to get rid of the text "with known demographics" on the page, but keep the metrics all the same
