### ISSUE TITLE
CDC: Asthma prevalence at the state level

### ISSUE THREAD

**Issue by ldbnr4** [SatcherInstitute/health-equity-tracker#92]
Data information: https://chronicdata.cdc.gov/Chronic-Disease-Indicators/U-S-Chronic-Disease-Indicators-Asthma/us8e-ubyj
API: https://chronicdata.cdc.gov/resource/us8e-ubyj.json
CSV Download: https://chronicdata.cdc.gov/api/views/us8e-ubyj/rows.csv?accessType=DOWNLOAD&api_foundry=true

**Comment by benhammondmusic** [comment]
implemented via AHR
