### ISSUE TITLE
CDC: Chronic Obstructive Pulmonary Disease at the state level

### ISSUE THREAD

**Issue by ldbnr4** [SatcherInstitute/health-equity-tracker#93]
Data information: https://chronicdata.cdc.gov/Chronic-Disease-Indicators/U-S-Chronic-Disease-Indicators-Chronic-Obstructive/aqr6-8kj8
API: https://chronicdata.cdc.gov/resource/aqr6-8kj8.json
CSV download: https://chronicdata.cdc.gov/api/views/aqr6-8kj8/rows.csv?accessType=DOWNLOAD

**Comment by benhammondmusic** [comment]
We are providing COPD data to the state level from AHR. Closing; but if we could find county level data we should use it
