### ISSUE TITLE
Add SHLI Logo to Footer

### ISSUE THREAD

**Issue by jgonzalezmsm** [SatcherInstitute/health-equity-tracker#936]
pending logo file from Mahia

**Comment by jgonzalezmsm** [comment]
![Satcher_logo2020_f](https://user-images.githubusercontent.com/81181322/120006855-4d2a6600-bfa7-11eb-9683-96dc3856a7ee.png)

**Comment by joshzarrabi** [comment]
Waiting on design input.

**Comment by benhammondmusic** [comment]
@joshzarrabi can we close this issue? Looks like logo is on footer. It isn't hyperlinked though which might be a good idea for uX and SEO

**Comment by jgonzalezmsm** [comment]
> @joshzarrabi can we close this issue? Looks like logo is on footer. It isn't hyperlinked though which might be a good idea for uX and SEO

sorry i didn't get to this in time. can we look into moving the SHLI logo to the right of the het logo? right now it's centered below everything else - that was a workaround because we didn't have you :). ideally we want it to fill in the space here: 

![image](https://user-images.githubusercontent.com/81181322/130157562-3e31c281-6d3f-4595-a6f2-e626120c4b6e.png)

Also, yes i think it's a good idea to link it

**Comment by jgonzalezmsm** [comment]
> > @joshzarrabi can we close this issue? Looks like logo is on footer. It isn't hyperlinked though which might be a good idea for uX and SEO
> 
> sorry i didn't get to this in time. can we look into moving the SHLI logo to the right of the het logo? right now it's centered below everything else - that was a workaround because we didn't have you :). ideally we want it to fill in the space here:
> 
> ![image](https://user-images.githubusercontent.com/81181322/130157562-3e31c281-6d3f-4595-a6f2-e626120c4b6e.png)
> 
> Also, yes i think it's a good idea to link it

we need to see how moving it there affect mobile - the reason we added it to the bottom was because it was a quick/easy way to make sure it would stack

**Comment by benhammondmusic** [comment]
Sure, I can play w this and see about getting a nice responsive layout that scales well for mobile/desktop
