### ISSUE TITLE
Review logic for and add checks for various metrics

### ISSUE THREAD

**Issue by vanshkumar** [SatcherInstitute/health-equity-tracker#958]
Currently, the METRIC_CONFIG in MetricConfig.ts is a bit ad-hoc: we have some metrics which require a populationComparisonMetric, there is the concept of a knownBreakdownComparisonMetric, etc. We should review the logic to make sure it is robust and generalizes as we want. One concrete example is that we should likely require a populationComparisonMetric for the count and pct_share metrics.

**Comment by kkatzen** [comment]
Where "reporting population" metrics are just using copied ACS data, let's remove those metric IDs and switch the MetricConfig to just using ACS population directly
