### ISSUE TITLE
Potentially improve dataset caching by caching individual results / metrics that are requested together

### ISSUE THREAD

**Issue by vanshkumar** [SatcherInstitute/health-equity-tracker#959]
See this todo in DataManager.ts:

![Screen Shot 2021-06-03 at 10 08 16 AM](https://user-images.githubusercontent.com/3394642/120684502-9e2cd500-c453-11eb-8a04-0e00a4f98048.png)

**Comment by aaronsn** [comment]
I think this probably isn't worth doing since I think it will add more complexity than it will help. Maybe we should just delete the TODO or turn into an FYI comment
