### ISSUE TITLE
Move standardized column name constants on the FE to a shared file

### ISSUE THREAD

**Issue by vanshkumar** [SatcherInstitute/health-equity-tracker#960]
We currently have a VAR_FIPS variable in ChoroplethMap.tsx which is equal to "fips"; we also use the same hard-coded string in the variable providers (along with others). These standardized column name constants should be moved to a shared file

**Comment by benhammondmusic** [comment]
closing as we have moved almost all calculations to the backend; most of the remaining "fips" are members of the BreakdownVar type which is enforced
