### ISSUE TITLE
Consider finding different library for joins, or write our own

### ISSUE THREAD

**Issue by vanshkumar** [SatcherInstitute/health-equity-tracker#964]
See todo in datasetutils.ts:
![Screen Shot 2021-06-03 at 10 21 48 AM](https://user-images.githubusercontent.com/3394642/120686126-82c2c980-c455-11eb-92ca-f977bc922452.png)

**Comment by benhammondmusic** [comment]
we are moving all dataset calculation and manipulation to the backend in #1474
