### ISSUE TITLE
Run an automated browser based test in our pipeline

### ISSUE THREAD

**Issue by joshzarrabi** [SatcherInstitute/health-equity-tracker#981]
### Background

Currently, in order to make sure the site still works as intended after we make any changes, we run an [e2e test](https://github.com/SatcherInstitute/health-equity-tracker/blob/master/e2e_tests/data_serving.py) which simply hits the a data endpoint on the frontend and makes sure the served json looks right. This is okay however does not simulate what a real user would do, which is to go to the browser and use the site.

### Proposed solution

In order to increase confidence in any changes we make, we should run an automated test script that clicks around the new site on a real browser to make sure it still works. This would give us much more confidence that any given change didn't break the site and would allow us to more quickly and confidently make changes to the live site. 

I have a small script that does this written in [element](https://element.flood.io/), however we can use any headless browser based tool to do this.

**Comment by benhammondmusic** [comment]
#1533
