### ISSUE TITLE
Puerto Rico Total Cases by Race and Ethnicity 

### ISSUE THREAD

**Issue by jgonzalezmsm** [SatcherInstitute/health-equity-tracker#993]
Puerto Rico Data is confusing in Total COVID-19 Cases By Race And Ethnicity due to calculation and high amount of unknowns + single race/ethnicity recorded. Results in both Hispanic and Latino and All categories showing 100%.

Proposal to remove "All" as a category from table and move to alert/info box similar to unknown map. 

Add an info bubble to the map card saying what the per100k number is for the overall geography
Remove “All” from the table card
Add “with known demographics” to the share of label text

Krista to make change, JC to write infobox text.

**Comment by vanshkumar** [comment]
Don't think the last change (add "with known demographics") is needed if we make the first two changes

**Comment by kkatzen** [comment]
Here's what I came up with for the map card:
![Screen Shot 2021-07-02 at 1 58 08 PM](https://user-images.githubusercontent.com/6402808/124328067-c3d5f880-db3d-11eb-9271-ae00976f70c5.png)
